import { tag } from "../../tag";

export const objectTags = [
  tag("airplane", {
    label: "Airplane",
    aliases: ["plane", "aircraft", "jet"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("anvil", {
    label: "Anvil",
    parents: ["crafting-station"],
    implies: ["crafting-station", "prop", "metalworking"],
  }),
  tag("arrow", {
    label: "Arrow",
    aliases: ["bolt"],
    parents: ["weapon"],
    implies: ["weapon", "tool", "wood"],
  }),
  tag("bag", {
    label: "Bag",
    aliases: ["pouch", "sack"],
    parents: ["storage"],
    implies: ["storage", "prop"],
  }),
  tag("barrel", {
    label: "Barrel",
    aliases: ["cask"],
    parents: ["storage"],
    implies: ["storage", "prop"],
  }),
  tag("basket", {
    label: "Basket",
    parents: ["storage"],
    implies: ["storage", "prop"],
  }),
  tag("bicycle", {
    label: "Bicycle",
    aliases: ["bike"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("blanket", {
    label: "Blanket",
    aliases: ["quilt"],
    parents: ["prop"],
    implies: ["prop", "fabric"],
  }),
  tag("boat", {
    label: "Boat",
    aliases: ["ship", "vessel"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop", "water"],
  }),
  tag("book", {
    label: "Book",
    aliases: ["notebook", "journal", "tome"],
    parents: ["prop"],
    implies: ["prop", "paper"],
  }),
  tag("bottle", {
    label: "Bottle",
    aliases: ["flask", "vial"],
    parents: ["storage"],
    implies: ["storage", "prop", "glass"],
  }),
  tag("bow", {
    label: "Bow",
    aliases: ["longbow", "shortbow"],
    parents: ["weapon"],
    implies: ["weapon", "tool", "wood"],
  }),
  tag("bowl", {
    label: "Bowl",
    aliases: ["mixing bowl"],
    parents: ["kitchenware"],
    implies: ["kitchenware", "prop", "ceramic"],
  }),
  tag("box", {
    label: "Box",
    aliases: ["crate"],
    parents: ["storage"],
    implies: ["storage", "prop"],
  }),
  tag("bucket", {
    label: "Bucket",
    aliases: ["pail"],
    parents: ["tool", "storage"],
    implies: ["tool", "storage", "prop"],
  }),
  tag("bus", {
    label: "Bus",
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("candle", {
    label: "Candle",
    aliases: ["wax candle"],
    parents: ["lighting"],
    implies: ["lighting", "prop"],
  }),
  tag("car", {
    label: "Car",
    aliases: ["automobile"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("clock", {
    label: "Clock",
    aliases: ["watch", "timepiece"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("cookware", {
    label: "Cookware",
    aliases: ["cooking vessel", "pots and pans"],
    parents: ["kitchenware"],
    implies: ["kitchenware", "prop", "cooking"],
  }),
  tag("crafting-station", {
    label: "Crafting Station",
    aliases: ["workstation", "skill station", "station"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("cup", {
    label: "Cup",
    aliases: ["mug", "glass", "teacup"],
    parents: ["kitchenware"],
    implies: ["kitchenware", "prop"],
  }),
  tag("curtain", {
    label: "Curtain",
    aliases: ["drape", "drapes"],
    parents: ["prop"],
    implies: ["prop", "fabric"],
  }),
  tag("fireplace", {
    label: "Fireplace",
    aliases: ["hearth"],
    parents: ["lighting", "building"],
    implies: ["lighting", "prop", "fire", "building"],
  }),
  tag("fishing-rod", {
    label: "Fishing Rod",
    aliases: ["rod", "fishing pole"],
    parents: ["tool"],
    implies: ["tool", "fishing"],
  }),
  tag("fork", {
    label: "Fork",
    aliases: ["dinner fork"],
    parents: ["utensil"],
    implies: ["utensil", "kitchenware", "prop"],
  }),
  tag("furnace", {
    label: "Furnace",
    aliases: ["forge", "smelter"],
    parents: ["crafting-station"],
    implies: ["crafting-station", "prop", "metalworking"],
  }),
  tag("hammer", {
    label: "Hammer",
    aliases: ["mallet"],
    parents: ["tool"],
    implies: ["tool", "metalworking"],
  }),
  tag("hatchet", {
    label: "Hatchet",
    aliases: ["axe"],
    parents: ["tool"],
    implies: ["tool", "woodcutting"],
  }),
  tag("hoe", {
    label: "Hoe",
    aliases: ["garden hoe", "farming hoe"],
    parents: ["tool"],
    implies: ["tool", "farming"],
  }),
  tag("jar", {
    label: "Jar",
    parents: ["storage"],
    implies: ["storage", "prop", "glass"],
  }),
  tag("jewelry", {
    label: "Jewelry",
    aliases: ["jewellery", "ring", "necklace", "bracelet"],
    parents: ["prop"],
    implies: ["prop", "metal"],
  }),
  tag("kitchenware", {
    label: "Kitchenware",
    aliases: ["kitchen item", "kitchen equipment"],
    parents: ["prop", "kitchen"],
    implies: ["prop", "kitchen"],
  }),
  tag("knife", {
    label: "Knife",
    aliases: ["dagger", "kitchen knife"],
    parents: ["tool", "utensil"],
    implies: ["tool", "utensil", "metal"],
  }),
  tag("lantern", {
    label: "Lantern",
    aliases: ["lamp", "light"],
    parents: ["lighting"],
    implies: ["lighting", "prop"],
  }),
  tag("lighting", {
    label: "Lighting",
    aliases: ["light", "illumination"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("pan", {
    label: "Pan",
    aliases: ["frying pan", "skillet", "saucepan"],
    parents: ["cookware"],
    implies: ["cookware", "kitchenware", "prop", "metal"],
  }),
  tag("paper", {
    label: "Paper",
    aliases: ["page", "parchment", "scroll"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("pickaxe", {
    label: "Pickaxe",
    aliases: ["pick"],
    parents: ["tool"],
    implies: ["tool", "mining"],
  }),
  tag("pillow", {
    label: "Pillow",
    aliases: ["cushion"],
    parents: ["prop"],
    implies: ["prop", "fabric"],
  }),
  tag("plate", {
    label: "Plate",
    aliases: ["dish", "serving plate"],
    parents: ["kitchenware"],
    implies: ["kitchenware", "prop", "ceramic"],
  }),
  tag("pot", {
    label: "Pot",
    aliases: ["cooking pot", "stockpot", "plant pot", "flower pot"],
    parents: ["cookware", "storage"],
    implies: ["cookware", "kitchenware", "storage", "prop"],
  }),
  tag("prop", {
    label: "Prop",
    aliases: ["set dressing", "decor"],
  }),
  tag("rake", {
    label: "Rake",
    aliases: ["garden rake", "leaf rake"],
    parents: ["tool"],
    implies: ["tool", "farming"],
  }),
  tag("range", {
    label: "Range",
    aliases: ["stove", "oven"],
    parents: ["crafting-station"],
    implies: ["crafting-station", "prop", "cooking"],
  }),
  tag("rope", {
    label: "Rope",
    aliases: ["cord", "line"],
    parents: ["tool"],
    implies: ["tool"],
  }),
  tag("rug", {
    label: "Rug",
    aliases: ["carpet", "mat"],
    parents: ["prop"],
    implies: ["prop", "fabric"],
  }),
  tag("shield", {
    label: "Shield",
    aliases: ["buckler", "kite shield", "round shield"],
    parents: ["tool"],
    implies: ["tool", "metal"],
  }),
  tag("shovel", {
    label: "Shovel",
    aliases: ["spade"],
    parents: ["tool"],
    implies: ["tool", "digging"],
  }),
  tag("sign", {
    label: "Sign",
    aliases: ["signage", "placard", "poster"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("spoon", {
    label: "Spoon",
    aliases: ["teaspoon", "tablespoon", "ladle"],
    parents: ["utensil"],
    implies: ["utensil", "kitchenware", "prop"],
  }),
  tag("storage", {
    label: "Storage",
    aliases: ["container", "containers"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("sword", {
    label: "Sword",
    aliases: ["blade"],
    parents: ["weapon"],
    implies: ["weapon", "tool", "metal"],
  }),
  tag("tool", {
    label: "Tool",
    aliases: ["equipment", "gear"],
  }),
  tag("torch", {
    label: "Torch",
    parents: ["lighting"],
    implies: ["lighting", "prop", "fire"],
  }),
  tag("train", {
    label: "Train",
    aliases: ["rail", "railway"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("truck", {
    label: "Truck",
    aliases: ["lorry"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
  tag("utensil", {
    label: "Utensil",
    aliases: ["cutlery", "silverware", "flatware"],
    parents: ["kitchenware", "tool"],
    implies: ["kitchenware", "tool", "prop"],
  }),
  tag("vase", {
    label: "Vase",
    aliases: ["flower vase", "urn"],
    parents: ["prop"],
    implies: ["prop", "ceramic"],
  }),
  tag("vehicle", {
    label: "Vehicle",
    aliases: ["transport", "transportation"],
    parents: ["prop"],
    implies: ["prop"],
  }),
  tag("weapon", {
    label: "Weapon",
    aliases: ["armament"],
    parents: ["tool"],
    implies: ["tool"],
  }),
  tag("wheel", {
    label: "Wheel",
    aliases: ["tire", "tyre"],
    parents: ["vehicle"],
    implies: ["vehicle", "prop"],
  }),
];
