import {
  Archive,
  BookOpen,
  Box,
  Briefcase,
  Brush,
  Camera,
  ClipboardList,
  Code2,
  Cog,
  FileAudio,
  FileCode,
  FileImage,
  FileText,
  Film,
  FolderOpen,
  Gamepad2,
  Globe2,
  Hammer,
  Home,
  Image,
  Leaf,
  Map,
  Music,
  Package,
  Palette,
  PenTool,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Tags,
  User,
  Wrench,
} from "lucide-react";

import { node } from "../node";
import type { LibraryNodeTemplate } from "../types";

// This catalog is bundled into the app installer. It is the shared vocabulary for building a personal Master Library.
export const libraryNodeTemplates: LibraryNodeTemplate[] = [
  node("all-assets", "All Assets", "Everything Inventory knows about, regardless of type or purpose.", "Foundation", FolderOpen, {
    aliases: ["master library", "everything", "all files"],
    suggestedTags: ["asset"],
    fileTypes: ["Any"],
    childSuggestions: ["3D Objects", "Images", "Audio", "Documents", "Source Files", "Archives"],
    matchRules: [{ field: "type", terms: ["Image", "3D", "Audio", "Document", "Archive"] }],
  }),

  node("3d-objects", "3D Objects", "Models, meshes, scenes, exports, and 3D-ready assets.", "Asset Type", Box, {
    aliases: ["models", "meshes", "glb", "gltf", "obj", "stl"],
    suggestedTags: ["3d", "model", "mesh"],
    fileTypes: ["3D"],
    childSuggestions: ["Characters", "Creatures", "Nature", "Buildings", "City", "Architecture", "Props", "Items", "Furniture", "Vehicles", "Weapons", "Food", "Tools", "Lighting", "Environment Pieces"],
    matchRules: [
      { field: "type", terms: ["3D"] },
      { field: "extension", terms: ["glb", "gltf", "obj", "stl", "fbx", "blend"] },
    ],
  }),
  node("characters", "Characters", "Playable characters, NPCs, people, outfits, body parts, rigs, and avatars.", "Subject", User, {
    aliases: ["people", "npc", "avatar", "humanoid", "player", "hero", "protagonist"],
    suggestedTags: ["character", "person", "npc", "avatar", "player"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Clothing", "Hair", "Hands", "Heads", "Rigs", "Animations"],
    matchRules: [{ field: "name", terms: ["character", "npc", "avatar", "person", "human", "humanoid", "player", "hero", "protagonist", "main character"] }],
  }),
  node("creatures", "Creatures", "Animals, monsters, fantasy beings, insects, and non-human characters.", "Subject", Sparkles, {
    aliases: ["animals", "monsters", "beasts", "critters", "wildlife"],
    suggestedTags: ["creature", "animal", "monster", "beast"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Animals", "Birds", "Farm Animals", "Fish", "Reptiles", "Insects", "Pets", "Monsters", "Fantasy Creatures"],
    matchRules: [
      {
        field: "name",
        terms: [
          "creature",
          "monster",
          "animal",
          "beast",
          "dragon",
          "bird",
          "chicken",
          "duck",
          "goose",
          "cow",
          "pig",
          "sheep",
          "goat",
          "horse",
          "dog",
          "cat",
          "fish",
          "frog",
          "snake",
          "lizard",
          "insect",
          "bug",
          "spider",
        ],
      },
    ],
  }),
  node("animals", "Animals", "Living animal assets, wildlife, farm animals, pets, birds, fish, reptiles, and fauna.", "Subject", Leaf, {
    aliases: ["wildlife", "fauna", "livestock", "pets"],
    suggestedTags: ["animal", "creature", "fauna"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Birds", "Farm Animals", "Fish", "Reptiles", "Insects", "Pets", "Wildlife"],
    matchRules: [
      {
        field: "name",
        terms: [
          "animal",
          "wildlife",
          "livestock",
          "pet",
          "bird",
          "chicken",
          "rooster",
          "hen",
          "duck",
          "goose",
          "turkey",
          "cow",
          "bull",
          "calf",
          "pig",
          "sheep",
          "lamb",
          "goat",
          "horse",
          "dog",
          "cat",
          "rabbit",
          "deer",
          "fox",
          "wolf",
          "bear",
          "fish",
          "frog",
          "snake",
          "lizard",
          "turtle",
          "insect",
          "bug",
          "spider",
        ],
      },
    ],
  }),
  node("birds", "Birds", "Bird assets, farm birds, flying creatures, nests, feathers, and avian references.", "Subject", Leaf, {
    aliases: ["avian", "fowl", "feathers"],
    suggestedTags: ["bird", "animal", "avian"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Flying Birds", "Nests", "Feathers"],
    matchRules: [
      {
        field: "name",
        terms: ["bird", "avian", "fowl", "chicken", "rooster", "hen", "chick", "duck", "goose", "swan", "crow", "raven", "eagle", "hawk", "owl", "parrot", "gull", "seagull", "turkey", "quail", "nest", "feather"],
      },
    ],
  }),
  node("farm-animals", "Farm Animals", "Livestock, barnyard animals, farm birds, stable animals, and rural creature assets.", "Subject", Home, {
    aliases: ["livestock", "barn animals", "barnyard", "farm creatures"],
    suggestedTags: ["farm", "animal", "livestock"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Birds", "Cattle", "Pigs", "Sheep", "Goats", "Horses"],
    matchRules: [
      {
        field: "name",
        terms: ["farm animal", "livestock", "barnyard", "farm", "chicken", "rooster", "hen", "chick", "duck", "goose", "turkey", "cow", "bull", "calf", "pig", "piglet", "sheep", "lamb", "goat", "horse", "pony", "donkey"],
      },
    ],
  }),
  node("fish", "Fish", "Fish, sea creatures, pond life, aquatic animals, fins, scales, and underwater fauna.", "Subject", Map, {
    aliases: ["aquatic animals", "sea creatures", "pond life"],
    suggestedTags: ["fish", "aquatic", "water", "animal"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Freshwater", "Saltwater", "Pond Life", "Aquatic Creatures"],
    matchRules: [{ field: "name", terms: ["fish", "aquatic", "sea creature", "pond", "koi", "carp", "trout", "salmon", "bass", "shark", "ray", "eel", "crab", "lobster", "shell", "scale", "fin"] }],
  }),
  node("reptiles", "Reptiles", "Reptiles, amphibians, snakes, lizards, turtles, frogs, and scaled creature assets.", "Subject", Leaf, {
    aliases: ["amphibians", "scaled animals"],
    suggestedTags: ["reptile", "animal", "creature"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Snakes", "Lizards", "Turtles", "Frogs"],
    matchRules: [{ field: "name", terms: ["reptile", "amphibian", "snake", "lizard", "turtle", "frog", "toad", "gecko", "iguana", "crocodile", "alligator", "scale"] }],
  }),
  node("insects", "Insects", "Insects, bugs, spiders, small creatures, wings, shells, and creepy-crawly assets.", "Subject", Sparkles, {
    aliases: ["bugs", "spiders", "creepy crawlies"],
    suggestedTags: ["insect", "bug", "creature"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Beetles", "Butterflies", "Spiders", "Wings"],
    matchRules: [{ field: "name", terms: ["insect", "bug", "spider", "beetle", "butterfly", "moth", "ant", "bee", "wasp", "fly", "wing", "web"] }],
  }),
  node("pets", "Pets", "Companion animals, domestic animals, pet props, collars, bowls, beds, and related assets.", "Subject", Home, {
    aliases: ["companion animals", "domestic animals"],
    suggestedTags: ["pet", "animal", "domestic"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Dogs", "Cats", "Pet Props"],
    matchRules: [{ field: "name", terms: ["pet", "dog", "cat", "puppy", "kitten", "rabbit", "hamster", "collar", "leash", "pet bowl", "pet bed"] }],
  }),
  node("props", "Props", "Reusable objects, set dressing, pickups, interactables, and decorative pieces.", "Subject", Package, {
    aliases: ["set dressing", "decorative props", "scene props"],
    suggestedTags: ["prop", "decor", "set-dressing"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Crafting Stations", "Furniture", "Storage", "Tools", "Weapons", "Food", "Lighting", "Containers", "Signs"],
    matchRules: [{ field: "name", terms: ["prop", "props", "decor", "decoration", "set dressing", "anvil", "furnace", "forge", "range", "station", "workbench", "statue", "vase", "sign", "banner", "barrel", "crate"] }],
  }),
  node("items", "Items", "Inventory items, pickups, collectibles, loot, small props, and reusable object assets.", "Subject", Package, {
    aliases: ["inventory items", "pickups", "collectibles", "loot"],
    suggestedTags: ["item", "pickup", "collectible"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Food", "Weapons", "Tools", "Containers", "Keys", "Currency", "Crafting Items"],
    matchRules: [{ field: "name", terms: ["item", "pickup", "collectible", "loot", "key", "coin"] }],
  }),
  node("food", "Food", "Food, drinks, ingredients, cooked meals, kitchen props, and edible item assets.", "Subject", Package, {
    aliases: ["ingredients", "meals", "drinks", "cooking"],
    suggestedTags: ["food", "ingredient", "meal", "drink"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Fruit", "Vegetables", "Meals", "Meat", "Drinks", "Ingredients", "Kitchen Props"],
    matchRules: [{ field: "name", terms: ["food", "fruit", "vegetable", "meal", "drink", "bread", "meat", "cook", "cooking", "kitchen", "stove", "oven", "range", "roast", "roasted", "grilled", "fried", "raw", "poultry", "drumstick", "fillet", "steak", "roast chicken", "fried chicken", "chicken meat", "chicken leg"] }],
  }),
  node("fruit", "Fruit", "Fruit assets, orchard produce, berries, citrus, tropical fruit, and edible plant props.", "Subject", Package, {
    aliases: ["fruits", "berries", "citrus"],
    suggestedTags: ["fruit", "food", "ingredient"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Berries", "Citrus", "Orchard Fruit", "Tropical Fruit"],
    matchRules: [{ field: "name", terms: ["fruit", "apple", "banana", "orange", "lemon", "lime", "pear", "peach", "plum", "cherry", "berry", "strawberry", "blueberry", "raspberry", "grape", "melon", "watermelon", "pineapple", "mango", "coconut"] }],
  }),
  node("vegetables", "Vegetables", "Vegetable assets, garden produce, roots, greens, mushrooms, and cooking ingredients.", "Subject", Package, {
    aliases: ["veg", "produce", "greens", "roots"],
    suggestedTags: ["vegetable", "food", "ingredient"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Root Vegetables", "Greens", "Mushrooms", "Herbs"],
    matchRules: [{ field: "name", terms: ["vegetable", "veg", "carrot", "potato", "onion", "garlic", "tomato", "pepper", "pumpkin", "corn", "cabbage", "lettuce", "broccoli", "mushroom", "herb"] }],
  }),
  node("meat", "Meat", "Meat, poultry, fish fillets, cooked proteins, raw cuts, bones, and food-prep assets.", "Subject", Package, {
    aliases: ["poultry", "protein", "raw meat", "cooked meat"],
    suggestedTags: ["meat", "food", "ingredient"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Poultry", "Fish Fillets", "Cooked Meat", "Raw Meat"],
    matchRules: [{ field: "name", terms: ["meat", "poultry", "steak", "fillet", "drumstick", "cutlet", "sausage", "bacon", "ham", "bone", "rib", "roast", "roasted", "grilled", "fried", "raw meat", "cooked meat", "roast chicken", "fried chicken", "chicken meat", "chicken leg"] }],
  }),
  node("meals", "Meals", "Complete meals, prepared dishes, plated food, soups, desserts, and cooked recipes.", "Subject", Package, {
    aliases: ["dishes", "prepared food", "recipes"],
    suggestedTags: ["meal", "food", "cooked"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Soups", "Desserts", "Plated Food", "Snacks"],
    matchRules: [{ field: "name", terms: ["meal", "dish", "recipe", "plated", "soup", "stew", "pie", "cake", "dessert", "snack", "sandwich", "pizza", "bread", "roast", "cooked"] }],
  }),
  node("drinks", "Drinks", "Drinks, bottles, cups, mugs, potions, beverages, and liquid food assets.", "Subject", Package, {
    aliases: ["beverages", "liquids", "potions"],
    suggestedTags: ["drink", "beverage", "food"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Bottles", "Cups", "Potions", "Hot Drinks"],
    matchRules: [{ field: "name", terms: ["drink", "beverage", "bottle", "cup", "mug", "glass", "potion", "tea", "coffee", "juice", "water", "milk", "ale", "beer", "wine"] }],
  }),
  node("ingredients", "Ingredients", "Recipe ingredients, raw food pieces, cooking components, spices, herbs, and prep assets.", "Subject", Package, {
    aliases: ["cooking ingredients", "raw ingredients", "spices"],
    suggestedTags: ["ingredient", "food", "cooking"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Fruit", "Vegetables", "Meat", "Herbs", "Spices"],
    matchRules: [{ field: "name", terms: ["ingredient", "raw", "spice", "herb", "flour", "sugar", "salt", "pepper", "oil", "egg", "milk", "cheese", "butter"] }],
  }),
  node("kitchen-props", "Kitchen Props", "Cooking equipment, stoves, ovens, ranges, cookware, plates, bowls, mugs, and kitchen dressing.", "Subject", Package, {
    aliases: ["cookware", "cooking props", "kitchenware"],
    suggestedTags: ["kitchen", "cooking", "cookware", "food"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Cookware", "Plates", "Bowls", "Cups", "Stoves", "Ovens"],
    matchRules: [{ field: "name", terms: ["kitchen", "cookware", "cook", "cooking", "stove", "oven", "range", "pot", "pan", "cauldron", "kettle", "plate", "bowl", "cup", "mug"] }],
  }),
  node("crafting-stations", "Crafting Stations", "Skill stations, crafting props, production workstations, furnaces, anvils, ranges, forges, and workbenches.", "Subject", Wrench, {
    aliases: ["workstations", "skill stations", "production stations", "crafting props"],
    suggestedTags: ["station", "crafting", "workstation", "prop"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Forges", "Cooking Stations", "Workbenches", "Production Stations"],
    matchRules: [
      {
        field: "name",
        terms: [
          "crafting station",
          "workstation",
          "work station",
          "skill station",
          "station",
          "anvil",
          "furnace",
          "forge",
          "smelter",
          "kiln",
          "range",
          "stove",
          "oven",
          "workbench",
          "crafting table",
          "loom",
          "sawmill",
          "grindstone",
          "cauldron",
          "alchemy table",
          "enchanting table",
          "blacksmith",
        ],
      },
    ],
  }),
  node("furniture", "Furniture", "Tables, chairs, beds, shelves, cabinets, counters, and room dressing.", "Subject", Home, {
    aliases: ["chair", "table", "bed", "shelf", "cabinet"],
    suggestedTags: ["furniture", "chair", "table", "shelf"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Seating", "Tables", "Storage", "Beds", "Shelving"],
    matchRules: [{ field: "name", terms: ["chair", "table", "bed", "shelf", "cabinet", "sofa"] }],
  }),
  node("storage", "Storage", "Chests, crates, barrels, boxes, containers, cabinets, and inventory objects.", "Subject", Archive, {
    aliases: ["containers", "chests", "crates", "barrels", "boxes"],
    suggestedTags: ["storage", "container", "chest", "crate", "barrel"],
    fileTypes: ["3D", "Image"],
    matchRules: [{ field: "name", terms: ["chest", "crate", "barrel", "box", "container", "storage"] }],
  }),
  node("architecture", "Architecture", "Buildings, walls, floors, roofs, doors, windows, stairs, and modular kits.", "Subject", Home, {
    aliases: ["buildings", "modular", "walls", "rooms"],
    suggestedTags: ["architecture", "building", "wall", "floor", "door"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Buildings", "Walls", "Floors", "Doors", "Windows", "Roofs", "Stairs", "Lighting"],
    matchRules: [{ field: "name", terms: ["building", "wall", "floor", "door", "window", "roof", "stair"] }],
  }),
  node("buildings", "Buildings", "Whole buildings, exterior shells, interiors, modular structures, houses, shops, and landmarks.", "Subject", Home, {
    aliases: ["building", "houses", "shops", "structures", "landmarks"],
    suggestedTags: ["building", "house", "structure"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Houses", "Shops", "Interiors", "Exteriors", "Landmarks", "Modular Buildings"],
    matchRules: [{ field: "name", terms: ["building", "house", "shop", "tower", "structure", "interior", "exterior"] }],
  }),
  node("city", "City", "Urban environments, streets, buildings, roads, vehicles, signs, and street-level props.", "Subject", Map, {
    aliases: ["urban", "town", "streets", "village"],
    suggestedTags: ["city", "urban", "street", "town"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Buildings", "Roads", "Vehicles", "Street Furniture", "Signs", "Lighting", "Sidewalks"],
    matchRules: [{ field: "name", terms: ["city", "urban", "street", "town", "road", "sidewalk"] }],
  }),
  node("roads", "Roads", "Roads, paths, streets, sidewalks, crossings, bridges, and route pieces.", "Subject", Map, {
    aliases: ["streets", "paths", "sidewalks", "routes"],
    suggestedTags: ["road", "street", "path", "sidewalk"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Streets", "Paths", "Sidewalks", "Crossings", "Bridges"],
    matchRules: [{ field: "name", terms: ["road", "street", "path", "sidewalk", "crossing", "bridge"] }],
  }),
  node("environment-pieces", "Environment Pieces", "Terrain, rocks, cliffs, paths, foliage, set pieces, and outdoor structures.", "Subject", Map, {
    aliases: ["environment", "level art", "terrain", "world pieces"],
    suggestedTags: ["environment", "terrain", "level", "world"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Terrain", "Nature", "City", "Rocks", "Foliage", "Water", "Roads", "Cliffs"],
    matchRules: [{ field: "tag", terms: ["environment", "terrain", "level", "world"] }],
  }),
  node("nature", "Nature", "Plants, trees, rocks, water, terrain, sky, weather, and organic scenery.", "Subject", Leaf, {
    aliases: ["plants", "trees", "rocks", "organic", "foliage", "natural", "forest", "woodland"],
    suggestedTags: ["nature", "plant", "tree", "rock", "water", "foliage", "terrain", "wood", "log", "bark"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Trees", "Plants", "Grass", "Rocks", "Water", "Sky", "Weather"],
    matchRules: [
      {
        field: "name",
        terms: [
          "tree",
          "plant",
          "rock",
          "water",
          "grass",
          "leaf",
          "stump",
          "trunk",
          "branch",
          "root",
          "log",
          "wood",
          "bark",
          "deadwood",
          "forest",
          "sapling",
          "pine",
          "oak",
          "birch",
          "bush",
          "flower",
          "fern",
          "vine",
          "foliage",
          "terrain",
          "stone",
          "boulder",
          "cliff",
        ],
      },
    ],
  }),
  node("trees", "Trees", "Tree models, trunks, branches, leaves, stumps, roots, and forest dressing.", "Subject", Leaf, {
    aliases: ["tree", "forest", "trunks", "branches", "saplings"],
    suggestedTags: ["tree", "forest", "wood", "leaf", "trunk", "branch", "stump"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Trunks", "Branches", "Leaves", "Stumps", "Roots", "Dead Trees"],
    matchRules: [{ field: "name", terms: ["tree", "trunk", "branch", "leaf", "stump", "root", "bark", "log", "sapling", "pine", "oak", "birch"] }],
  }),
  node("plants", "Plants", "Plants, bushes, flowers, ferns, vines, crops, and small foliage assets.", "Subject", Leaf, {
    aliases: ["foliage", "bushes", "flowers", "vines"],
    suggestedTags: ["plant", "foliage", "flower", "bush"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Flowers", "Bushes", "Ferns", "Vines", "Crops"],
    matchRules: [{ field: "name", terms: ["plant", "flower", "bush", "fern", "vine", "crop", "foliage"] }],
  }),
  node("grass", "Grass", "Grass clumps, ground cover, weeds, meadow pieces, and small terrain foliage.", "Subject", Leaf, {
    aliases: ["ground cover", "weeds", "meadow"],
    suggestedTags: ["grass", "ground-cover", "weed"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Grass Clumps", "Ground Cover", "Weeds", "Meadow"],
    matchRules: [{ field: "name", terms: ["grass", "weed", "meadow", "groundcover", "ground cover"] }],
  }),
  node("rocks", "Rocks", "Rocks, stones, boulders, cliffs, pebbles, ore pieces, and mineral dressing.", "Subject", Map, {
    aliases: ["stones", "boulders", "cliffs", "pebbles"],
    suggestedTags: ["rock", "stone", "boulder", "cliff"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Boulders", "Cliffs", "Pebbles", "Ore", "Stone Walls"],
    matchRules: [{ field: "name", terms: ["rock", "stone", "boulder", "cliff", "pebble", "ore"] }],
  }),
  node("water", "Water", "Water surfaces, rivers, lakes, ocean pieces, waterfalls, wet materials, and water effects.", "Subject", Map, {
    aliases: ["river", "lake", "ocean", "waterfall"],
    suggestedTags: ["water", "river", "lake", "ocean"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Rivers", "Lakes", "Ocean", "Waterfalls", "Wet Materials"],
    matchRules: [{ field: "name", terms: ["water", "river", "lake", "ocean", "waterfall", "wet"] }],
  }),
  node("vehicles", "Vehicles", "Cars, boats, aircraft, carts, ships, trains, mounts, and transport props.", "Subject", Cog, {
    aliases: ["transport", "car", "boat", "ship", "cart"],
    suggestedTags: ["vehicle", "transport", "car", "boat"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Cars", "Ships", "Aircraft", "Carts", "Trains"],
    matchRules: [{ field: "name", terms: ["vehicle", "car", "boat", "ship", "cart", "train"] }],
  }),
  node("weapons", "Weapons", "Melee weapons, firearms, projectiles, fantasy weapons, and combat props.", "Subject", Hammer, {
    aliases: ["sword", "gun", "bow", "combat"],
    suggestedTags: ["weapon", "sword", "gun", "bow"],
    fileTypes: ["3D", "Image", "Audio"],
    childSuggestions: ["Melee", "Ranged", "Projectiles", "Fantasy Weapons"],
    matchRules: [{ field: "name", terms: ["weapon", "sword", "axe", "gun", "bow", "arrow"] }],
  }),
  node("tools", "Tools", "Hand tools, utility objects, crafting items, workshop props, and equipment.", "Subject", Wrench, {
    aliases: ["equipment", "crafting", "workshop", "hand tools", "gear"],
    suggestedTags: ["tool", "equipment", "crafting", "utility", "gear"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Hand Tools", "Workshop", "Crafting", "Crafting Stations", "Fishing Gear", "Machinery"],
    matchRules: [{ field: "name", terms: ["tool", "hammer", "wrench", "pickaxe", "pick axe", "hatchet", "axe", "shovel", "saw", "chisel", "hoe", "rake", "tongs", "anvil", "blacksmith", "furnace", "forge", "workbench", "station", "fishing rod", "fishing", "rod", "pole", "tackle"] }],
  }),
  node("fishing-gear", "Fishing Gear", "Fishing rods, tackle, hooks, lures, nets, poles, reels, bait, and angling equipment.", "Subject", Wrench, {
    aliases: ["fishing tools", "tackle", "angling gear"],
    suggestedTags: ["fishing", "tool", "gear", "tackle"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Rods", "Hooks", "Lures", "Nets", "Bait"],
    matchRules: [{ field: "name", terms: ["fishing", "fishing rod", "rod", "fishing pole", "pole", "reel", "tackle", "hook", "lure", "bait", "net", "angler", "angling"] }],
  }),
  node("lighting", "Lighting", "Lamps, lanterns, torches, sconces, candles, streetlights, light posts, and emissive props.", "Subject", Sparkles, {
    aliases: ["lights", "lamps", "lanterns", "illumination"],
    suggestedTags: ["lighting", "light", "lamp", "lantern", "torch"],
    fileTypes: ["3D", "Image"],
    childSuggestions: ["Lanterns", "Torches", "Lamp Posts", "Streetlights", "Candles", "Sconces"],
    matchRules: [{ field: "name", terms: ["light", "lighting", "lamp", "lantern", "torch", "sconce", "candle", "chandelier", "streetlight", "lamppost", "lamp post"] }],
  }),

  node("images", "Images", "Raster, vector, visual reference, artwork, textures, photos, and interface graphics.", "Asset Type", FileImage, {
    aliases: ["image files", "pictures", "graphics", "png", "jpg", "svg"],
    suggestedTags: ["image", "visual"],
    fileTypes: ["Image"],
    childSuggestions: ["Photos", "Textures", "Icons", "UI", "Concept Art", "Sprites", "References"],
    matchRules: [
      { field: "type", terms: ["Image"] },
      { field: "extension", terms: ["png", "jpg", "jpeg", "webp", "avif", "svg"] },
    ],
  }),
  node("photos", "Photos", "Camera photos, reference photography, scans, captures, and real-world visual material.", "Image", Camera, {
    aliases: ["photography", "pictures", "camera"],
    suggestedTags: ["photo", "photography", "reference"],
    fileTypes: ["Image"],
    childSuggestions: ["People", "Environment", "Objects", "Nature", "Textures"],
    matchRules: [{ field: "name", terms: ["photo", "camera", "dsc", "img"] }],
  }),
  node("textures", "Textures", "Albedo, normal, roughness, metallic, masks, trims, and surface maps.", "Image", Image, {
    aliases: ["materials", "maps", "surface", "pbr"],
    suggestedTags: ["texture", "material", "map", "pbr"],
    fileTypes: ["Image", "3D"],
    childSuggestions: ["Albedo", "Normal Maps", "Roughness", "Metallic", "Masks", "Trims"],
    matchRules: [{ field: "name", terms: ["albedo", "normal", "roughness", "metallic", "diffuse", "texture"] }],
  }),
  node("icons", "Icons", "Small symbols, app icons, inventory art, item icons, status icons, and pictograms.", "Image", Tags, {
    aliases: ["symbols", "pictograms", "inventory icons"],
    suggestedTags: ["icon", "symbol", "pictogram"],
    fileTypes: ["Image"],
    childSuggestions: ["Inventory Icons", "Status Icons", "Tool Icons", "Navigation Icons"],
    matchRules: [{ field: "name", terms: ["icon", "symbol", "glyph", "pictogram"] }],
  }),
  node("ui", "UI", "Interface artwork, HUD elements, buttons, panels, cursors, overlays, and menus.", "Image", Gamepad2, {
    aliases: ["interface", "hud", "gui", "menus"],
    suggestedTags: ["ui", "interface", "hud", "button"],
    fileTypes: ["Image", "Document"],
    childSuggestions: ["Buttons", "Panels", "HUD", "Menus", "Cursors", "Inventory UI"],
    matchRules: [{ field: "tag", terms: ["ui", "hud", "interface", "button", "menu"] }],
  }),
  node("concept-art", "Concept Art", "Exploratory artwork, sketches, mood paintings, production art, and visual direction.", "Image", Brush, {
    aliases: ["art", "sketch", "painting", "visual development"],
    suggestedTags: ["concept", "art", "sketch", "mood"],
    fileTypes: ["Image", "Document"],
    childSuggestions: ["Characters", "Environments", "Props", "Mood Art"],
    matchRules: [{ field: "name", terms: ["concept", "sketch", "paint", "mood"] }],
  }),
  node("sprites", "Sprites", "2D sprites, animation frames, pixel art sheets, tiles, and sprite atlases.", "Image", Film, {
    aliases: ["2d", "pixel art", "sprite sheet", "atlas"],
    suggestedTags: ["sprite", "2d", "pixel", "atlas"],
    fileTypes: ["Image"],
    childSuggestions: ["Characters", "Tiles", "Effects", "Items", "Sprite Sheets"],
    matchRules: [{ field: "name", terms: ["sprite", "atlas", "sheet", "tile", "pixel"] }],
  }),
  node("screenshots", "Screenshots", "Screen captures, app captures, game captures, visual bug reports, and UI references.", "Image", Camera, {
    aliases: ["captures", "screen grabs", "screenies"],
    suggestedTags: ["screenshot", "capture"],
    fileTypes: ["Image"],
    matchRules: [{ field: "name", terms: ["screenshot", "screen", "capture"] }],
  }),

  node("audio", "Audio", "Sound effects, music, ambience, voice, raw recordings, and implementation references.", "Asset Type", FileAudio, {
    aliases: ["sound", "sfx", "music", "wav", "mp3"],
    suggestedTags: ["audio", "sound"],
    fileTypes: ["Audio"],
    childSuggestions: ["Sound Effects", "Music", "Ambience", "Voice", "Recordings"],
    matchRules: [
      { field: "type", terms: ["Audio"] },
      { field: "extension", terms: ["wav", "mp3", "ogg", "flac", "aiff", "m4a"] },
    ],
  }),
  node("sound-effects", "Sound Effects", "Impacts, UI sounds, footsteps, item sounds, whooshes, and one-shot effects.", "Audio", FileAudio, {
    aliases: ["sfx", "fx", "effects", "sound effects", "sound effect", "one shots", "one-shot", "oneshot", "foley"],
    suggestedTags: ["sfx", "effect", "sound", "impact"],
    fileTypes: ["Audio"],
    childSuggestions: ["UI Sounds", "Footsteps", "Impacts", "Weapons", "Items"],
    matchRules: [
      {
        field: "name",
        terms: [
          "sfx",
          "fx",
          "effect",
          "sound effect",
          "sound effects",
          "sound fx",
          "one shot",
          "one-shot",
          "oneshot",
          "foley",
          "hit",
          "impact",
          "click",
          "tap",
          "pop",
          "beep",
          "step",
          "footstep",
          "whoosh",
          "pickup",
          "drop",
          "open",
          "close",
          "door",
          "chest",
          "coin",
          "button",
          "confirm",
          "select",
          "jump",
          "land",
          "chop",
          "chopping",
          "axe",
          "swing",
          "slash",
          "punch",
          "explosion",
          "explode",
          "attack",
          "cast",
          "collect",
          "damage",
          "death",
          "equip",
          "error",
          "fail",
          "fireball",
          "gun",
          "hover",
          "hurt",
          "item",
          "laser",
          "lose",
          "magic",
          "menu",
          "reload",
          "shoot",
          "shot",
          "spawn",
          "spell",
          "success",
          "anvil",
          "thud",
          "bang",
          "boom",
          "bump",
          "crack",
          "crash",
          "smash",
          "snap",
          "slam",
          "collide",
          "collision",
          "knock",
          "clank",
          "clang",
          "hammer",
          "strike",
          "unequip",
          "weapon",
          "win",
        ],
      },
    ],
  }),
  node("music", "Music", "Loops, tracks, stems, sketches, themes, and soundtrack material.", "Audio", Music, {
    aliases: ["songs", "tracks", "loops", "score"],
    suggestedTags: ["music", "track", "loop", "score"],
    fileTypes: ["Audio"],
    childSuggestions: ["Loops", "Themes", "Stems", "Sketches"],
    matchRules: [{ field: "name", terms: ["music", "loop", "track", "theme", "stem"] }],
  }),
  node("ambience", "Ambience", "Environmental beds, room tone, weather, nature loops, and background audio.", "Audio", Globe2, {
    aliases: ["ambient", "background", "atmosphere"],
    suggestedTags: ["ambience", "ambient", "atmosphere"],
    fileTypes: ["Audio"],
    childSuggestions: ["Nature", "Interior", "Weather", "Crowds", "Machinery"],
    matchRules: [{ field: "name", terms: ["ambience", "ambient", "atmo", "roomtone", "weather"] }],
  }),
  node("voice", "Voice", "Dialogue, narration, vocal references, voiceover, barks, and character audio.", "Audio", User, {
    aliases: ["dialogue", "voiceover", "vo", "narration"],
    suggestedTags: ["voice", "dialogue", "vo", "narration"],
    fileTypes: ["Audio"],
    childSuggestions: ["Dialogue", "Narration", "Barks", "Scratch VO"],
    matchRules: [{ field: "name", terms: ["voice", "vo", "dialogue", "narration", "line"] }],
  }),

  node("documents", "Documents", "PDFs, Markdown, notes, text files, spreadsheets, licenses, and planning material.", "Asset Type", FileText, {
    aliases: ["docs", "references", "text", "pdf", "markdown"],
    suggestedTags: ["document", "doc", "reference"],
    fileTypes: ["Document"],
    childSuggestions: ["PDFs", "Notes", "Tutorials", "Planning", "Licenses", "Receipts", "Research"],
    matchRules: [
      { field: "type", terms: ["Document"] },
      { field: "extension", terms: ["pdf", "md", "txt", "json", "csv", "yaml", "xml"] },
    ],
  }),
  node("pdfs", "PDFs", "PDF references, manuals, invoices, receipts, exported docs, and source proofs.", "Document", ScrollText, {
    aliases: ["manuals", "papers", "exported docs"],
    suggestedTags: ["pdf", "document"],
    fileTypes: ["Document"],
    childSuggestions: ["Manuals", "Licenses", "Receipts", "Research"],
    matchRules: [{ field: "extension", terms: ["pdf"] }],
  }),
  node("notes", "Notes", "Markdown, text notes, reminders, project context, lore, research, and scratchpads.", "Document", ClipboardList, {
    aliases: ["markdown", "txt", "memo", "scratch"],
    suggestedTags: ["note", "markdown", "text"],
    fileTypes: ["Document"],
    childSuggestions: ["Project Notes", "Research Notes", "Ideas", "Lore"],
    matchRules: [{ field: "extension", terms: ["md", "txt"] }],
  }),
  node("tutorials", "Tutorials", "Guides, saved lessons, how-to material, walkthroughs, and implementation references.", "Document", BookOpen, {
    aliases: ["guides", "lessons", "how to", "walkthroughs"],
    suggestedTags: ["tutorial", "guide", "learning"],
    fileTypes: ["Document", "Image", "Audio"],
    matchRules: [{ field: "name", terms: ["tutorial", "guide", "lesson", "howto", "walkthrough"] }],
  }),
  node("planning", "Planning", "Design docs, task lists, schedules, outlines, architecture, and project maps.", "Document", Map, {
    aliases: ["design docs", "plans", "tasks", "roadmaps"],
    suggestedTags: ["planning", "design", "tasks", "roadmap"],
    fileTypes: ["Document"],
    childSuggestions: ["Design Docs", "Task Lists", "Roadmaps", "Architecture"],
    matchRules: [{ field: "name", terms: ["plan", "design", "roadmap", "tasks", "todo"] }],
  }),
  node("licenses", "Licenses", "License files, attribution requirements, source terms, and usage constraints.", "Legal", ShieldCheck, {
    aliases: ["license", "legal", "attribution", "terms"],
    suggestedTags: ["license", "legal", "attribution"],
    fileTypes: ["Document"],
    childSuggestions: ["Commercial Use", "Attribution Required", "License Unknown"],
    matchRules: [{ field: "name", terms: ["license", "licence", "legal", "attribution", "terms"] }],
  }),
  node("receipts", "Receipts", "Purchase receipts, invoices, order confirmations, and proof of ownership.", "Legal", Briefcase, {
    aliases: ["invoice", "purchase", "order", "proof"],
    suggestedTags: ["receipt", "invoice", "purchase"],
    fileTypes: ["Document", "Image"],
    matchRules: [{ field: "name", terms: ["receipt", "invoice", "order", "purchase"] }],
  }),

  node("source-files", "Source Files", "Editable originals, project files, working documents, and authoring-tool assets.", "Source", FileCode, {
    aliases: ["originals", "working files", "editable", "project files"],
    suggestedTags: ["source", "editable", "original"],
    fileTypes: ["Source", "Document", "Image", "3D"],
    childSuggestions: ["Blender", "Photoshop", "Illustrator", "Godot", "Unity", "Unreal", "Code"],
    matchRules: [{ field: "tag", terms: ["source", "original", "editable"] }],
  }),
  node("blender", "Blender", "Blend files, Blender exports, linked assets, references, and source scenes.", "Source", Box, {
    aliases: ["blend", "bpy", "blender source"],
    suggestedTags: ["blender", "blend", "source"],
    fileTypes: ["Source", "3D"],
    matchRules: [{ field: "extension", terms: ["blend"] }],
  }),
  node("photoshop", "Photoshop", "PSD files, layered image sources, design comps, and editable artwork.", "Source", FileImage, {
    aliases: ["psd", "photoshop source", "layered"],
    suggestedTags: ["photoshop", "psd", "source"],
    fileTypes: ["Source", "Image"],
    matchRules: [{ field: "extension", terms: ["psd", "psb"] }],
  }),
  node("illustrator", "Illustrator", "AI files, vector originals, logos, marks, layouts, and print-ready art.", "Source", PenTool, {
    aliases: ["ai", "vector", "illustrator source"],
    suggestedTags: ["illustrator", "vector", "source"],
    fileTypes: ["Source", "Image"],
    matchRules: [{ field: "extension", terms: ["ai", "eps", "svg"] }],
  }),
  node("godot", "Godot", "Godot scenes, resources, scripts, exports, and project-specific assets.", "Source", Gamepad2, {
    aliases: ["tscn", "tres", "gdscript", "godot project"],
    suggestedTags: ["godot", "game", "source"],
    fileTypes: ["Source", "Document"],
    matchRules: [{ field: "extension", terms: ["tscn", "tres", "gd", "godot"] }],
  }),
  node("unity", "Unity", "Unity packages, prefabs, scenes, materials, scripts, and project assets.", "Source", Gamepad2, {
    aliases: ["unity project", "prefab", "unitypackage"],
    suggestedTags: ["unity", "game", "source"],
    fileTypes: ["Source", "Archive", "Document"],
    matchRules: [{ field: "extension", terms: ["unity", "prefab", "unitypackage", "mat"] }],
  }),
  node("code", "Code", "Scripts, snippets, source code, shaders, config files, and implementation notes.", "Source", Code2, {
    aliases: ["scripts", "programming", "shader", "config"],
    suggestedTags: ["code", "script", "shader", "config"],
    fileTypes: ["Source", "Document"],
    childSuggestions: ["Scripts", "Shaders", "Config", "Snippets"],
    matchRules: [{ field: "extension", terms: ["ts", "tsx", "js", "py", "rs", "gd", "shader", "json"] }],
  }),

  node("archives", "Archives", "Compressed downloads, marketplace packs, backups, bundles, and packaged assets.", "Asset Type", Archive, {
    aliases: ["zip", "rar", "7z", "package", "bundle"],
    suggestedTags: ["archive", "pack", "bundle"],
    fileTypes: ["Archive"],
    childSuggestions: ["Marketplace Packs", "Backups", "Downloads"],
    matchRules: [
      { field: "type", terms: ["Archive"] },
      { field: "extension", terms: ["zip", "rar", "7z", "tar", "gz"] },
    ],
  }),
  node("marketplace-packs", "Marketplace Packs", "Downloaded asset packs, store bundles, creator packs, and purchased collections.", "Source", Briefcase, {
    aliases: ["asset packs", "store packs", "downloads", "bundle"],
    suggestedTags: ["marketplace", "asset-pack", "download"],
    fileTypes: ["Archive", "Any"],
    matchRules: [{ field: "path", terms: ["marketplace", "asset pack", "downloads", "store"] }],
  }),

  node("realistic", "Realistic", "Assets aiming for believable, grounded, or physically plausible presentation.", "Style", Camera, {
    aliases: ["grounded", "natural", "believable"],
    suggestedTags: ["realistic", "grounded"],
    fileTypes: ["Any"],
    matchRules: [{ field: "tag", terms: ["realistic", "grounded", "natural"] }],
  }),
  node("stylized", "Stylized", "Assets with expressive, simplified, painterly, or non-realistic direction.", "Style", Palette, {
    aliases: ["cartoon", "expressive", "painterly"],
    suggestedTags: ["stylized", "cartoon", "painterly"],
    fileTypes: ["Any"],
    matchRules: [{ field: "tag", terms: ["stylized", "cartoon", "painterly"] }],
  }),
  node("low-poly", "Low Poly", "Low-poly, optimized, simple geometry, retro 3D, and flat-shaded assets.", "Style", Box, {
    aliases: ["lowpoly", "flat shaded", "simple geometry"],
    suggestedTags: ["low-poly", "lowpoly", "optimized"],
    fileTypes: ["3D", "Image"],
    matchRules: [{ field: "name", terms: ["lowpoly", "low-poly", "low poly"] }],
  }),
  node("mid-poly", "Mid Poly", "Moderate-detail 3D models with balanced geometry for real-time use.", "Style", Box, {
    aliases: ["medium poly", "medium-poly", "balanced geometry"],
    suggestedTags: ["mid-poly", "medium-poly"],
    fileTypes: ["3D"],
    matchRules: [{ field: "tag", terms: ["mid-poly", "medium-poly"] }],
  }),
  node("high-poly", "High Poly", "High-detail 3D models with heavier geometry, dense meshes, or close-up detail.", "Style", Box, {
    aliases: ["highpoly", "dense mesh", "high detail"],
    suggestedTags: ["high-poly", "highpoly"],
    fileTypes: ["3D"],
    matchRules: [{ field: "tag", terms: ["high-poly", "highpoly"] }],
  }),
  node("very-high-poly", "Very High Poly", "Very dense 3D models suited for baking, close inspection, or source-quality reference.", "Style", Box, {
    aliases: ["very high poly", "dense geometry", "source quality"],
    suggestedTags: ["very-high-poly", "dense"],
    fileTypes: ["3D"],
    matchRules: [{ field: "tag", terms: ["very-high-poly", "dense"] }],
  }),
  node("pixel-art", "Pixel Art", "Pixel sprites, tiles, pixel UI, palettes, sprite sheets, and retro 2D art.", "Style", Image, {
    aliases: ["pixel", "retro", "8-bit", "16-bit"],
    suggestedTags: ["pixel", "pixel-art", "retro"],
    fileTypes: ["Image"],
    matchRules: [{ field: "name", terms: ["pixel", "8bit", "16bit", "retro"] }],
  }),
  node("sci-fi", "Sci-Fi", "Science fiction, futuristic, space, cyberpunk, robotics, and technology assets.", "Genre", Cog, {
    aliases: ["science fiction", "future", "space", "cyberpunk"],
    suggestedTags: ["sci-fi", "future", "space", "tech"],
    fileTypes: ["Any"],
    matchRules: [{ field: "tag", terms: ["sci-fi", "scifi", "future", "space", "cyberpunk"] }],
  }),
  node("fantasy", "Fantasy", "Medieval fantasy, magic, creatures, castles, taverns, spells, and mythic assets.", "Genre", Sparkles, {
    aliases: ["magic", "medieval", "mythic", "rpg"],
    suggestedTags: ["fantasy", "magic", "medieval"],
    fileTypes: ["Any"],
    matchRules: [{ field: "tag", terms: ["fantasy", "magic", "medieval", "rpg"] }],
  }),
  node("historical", "Historical", "Period references, historical props, architecture, documents, and costumes.", "Genre", BookOpen, {
    aliases: ["period", "old", "antique", "heritage"],
    suggestedTags: ["historical", "period", "antique"],
    fileTypes: ["Any"],
    matchRules: [{ field: "tag", terms: ["historical", "period", "antique", "vintage"] }],
  }),
];
