import { tag } from "../../tag";

export const attractionTags = [
  tag("amusement-park", {
    label: "Amusement Park",
    aliases: ["theme park", "funfair"],
    parents: ["attraction"],
    implies: ["attraction"],
  }),
  tag("aquarium", {
    label: "Aquarium",
    aliases: ["sea life centre"],
    parents: ["attraction", "building"],
    implies: ["attraction", "building", "fish"],
  }),
  tag("attraction", {
    label: "Attraction",
    aliases: ["place of interest", "destination"],
    related: ["travel", "landmark"],
  }),
  tag("botanical-garden", {
    label: "Botanical Garden",
    aliases: ["botanic garden", "plant garden"],
    parents: ["garden", "attraction"],
    implies: ["garden", "attraction", "plant"],
  }),
  tag("coastal-attraction", {
    label: "Coastal Attraction",
    aliases: ["seaside attraction", "waterfront attraction"],
    parents: ["attraction"],
    implies: ["attraction", "coastal"],
  }),
  tag("festival-ground", {
    label: "Festival Ground",
    aliases: ["fairground", "event ground"],
    parents: ["attraction"],
    implies: ["attraction"],
    related: ["music", "dancing"],
  }),
  tag("fountain", {
    label: "Fountain",
    aliases: ["water fountain"],
    parents: ["landmark"],
    implies: ["landmark", "water"],
  }),
  tag("garden", {
    label: "Garden",
    aliases: ["yard", "formal garden"],
    parents: ["attraction", "nature"],
    implies: ["nature", "plant"],
  }),
  tag("landmark", {
    label: "Landmark",
    aliases: ["monumental place", "iconic place"],
    parents: ["attraction"],
    implies: ["attraction"],
  }),
  tag("market", {
    label: "Market",
    aliases: ["bazaar", "marketplace", "stall market"],
    parents: ["attraction"],
    implies: ["attraction"],
    related: ["shop", "food"],
  }),
  tag("memorial", {
    label: "Memorial",
    aliases: ["remembrance site", "commemorative monument"],
    parents: ["monument"],
    implies: ["monument", "landmark", "attraction"],
  }),
  tag("monument", {
    label: "Monument",
    aliases: ["statue monument", "public monument"],
    parents: ["landmark"],
    implies: ["landmark", "attraction"],
  }),
  tag("museum", {
    label: "Museum",
    aliases: ["gallery museum", "exhibition hall"],
    parents: ["attraction", "building"],
    implies: ["attraction", "building"],
    related: ["history"],
  }),
  tag("national-park", {
    label: "National Park",
    aliases: ["protected park", "nature reserve"],
    parents: ["park", "attraction"],
    implies: ["park", "attraction", "nature"],
  }),
  tag("observatory", {
    label: "Observatory",
    aliases: ["astronomical observatory", "stargazing site"],
    parents: ["attraction", "building"],
    implies: ["attraction", "building"],
    related: ["stars"],
  }),
  tag("park", {
    label: "Park",
    aliases: ["public park", "green space"],
    parents: ["attraction"],
    implies: ["attraction", "nature"],
  }),
  tag("pier", {
    label: "Pier",
    aliases: ["jetty", "boardwalk"],
    parents: ["coastal-attraction"],
    implies: ["coastal-attraction", "attraction"],
  }),
  tag("temple-attraction", {
    label: "Temple Attraction",
    aliases: ["temple site", "sacred site"],
    parents: ["landmark"],
    implies: ["landmark", "attraction"],
    related: ["temple-building"],
  }),
  tag("viewpoint", {
    label: "Viewpoint",
    aliases: ["lookout", "scenic overlook"],
    parents: ["attraction"],
    implies: ["attraction"],
    related: ["landscape"],
  }),
  tag("zoo", {
    label: "Zoo",
    aliases: ["wildlife park", "animal park"],
    parents: ["attraction"],
    implies: ["attraction", "animal"],
  }),
];
