import { tag } from "../../tag";

export const buildingTags = [
  tag("apartment-building", {
    label: "Apartment Building",
    aliases: ["apartments", "flats", "residential block"],
    parents: ["building"],
    implies: ["building", "home", "architecture"],
  }),
  tag("architecture", {
    label: "Architecture",
    aliases: ["architectural", "built environment"],
  }),
  tag("barn", {
    label: "Barn",
    aliases: ["stable", "hayloft"],
    parents: ["farm", "building"],
    implies: ["farm", "building", "architecture"],
  }),
  tag("bridge", {
    label: "Bridge",
    aliases: ["overpass", "viaduct"],
    parents: ["architecture"],
    related: ["road", "river"],
  }),
  tag("building", {
    label: "Building",
    aliases: ["structure", "built structure"],
    parents: ["architecture"],
    implies: ["architecture"],
  }),
  tag("cabin", {
    label: "Cabin",
    aliases: ["log cabin", "hut"],
    parents: ["home"],
    implies: ["home", "building", "architecture"],
  }),
  tag("castle", {
    label: "Castle",
    aliases: ["fort", "fortress", "tower keep"],
    parents: ["building"],
    implies: ["building", "architecture"],
  }),
  tag("cathedral", {
    label: "Cathedral",
    aliases: ["minster", "large church"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["landmark"],
  }),
  tag("cottage", {
    label: "Cottage",
    aliases: ["country house", "small house"],
    parents: ["home"],
    implies: ["home", "building", "architecture"],
  }),
  tag("factory", {
    label: "Factory",
    aliases: ["plant", "industrial building"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["industry"],
  }),
  tag("farm", {
    label: "Farm",
    aliases: ["ranch", "homestead"],
    parents: ["building", "countryside"],
    implies: ["building", "farming"],
  }),
  tag("greenhouse", {
    label: "Greenhouse",
    aliases: ["glasshouse", "conservatory"],
    parents: ["building", "garden"],
    implies: ["building", "plant"],
  }),
  tag("hospital-building", {
    label: "Hospital",
    aliases: ["clinic", "medical centre"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["healthcare"],
  }),
  tag("hotel", {
    label: "Hotel",
    aliases: ["inn", "motel", "guesthouse"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["travel"],
  }),
  tag("home", {
    label: "House",
    aliases: ["home", "residence", "dwelling"],
    parents: ["building"],
    implies: ["building", "architecture"],
  }),
  tag("lighthouse", {
    label: "Lighthouse",
    aliases: ["beacon tower"],
    parents: ["tower", "coastal-attraction"],
    implies: ["building", "architecture"],
    related: ["coastal"],
  }),
  tag("palace", {
    label: "Palace",
    aliases: ["royal residence", "chateau"],
    parents: ["home", "landmark"],
    implies: ["home", "building", "architecture"],
  }),
  tag("ruin", {
    label: "Ruin",
    aliases: ["ruins", "abandoned building", "wreck", "derelict", "dilapidated building"],
    parents: ["building"],
    implies: ["building", "architecture"],
  }),
  tag("school-building", {
    label: "School",
    aliases: ["academy", "campus building"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["education"],
  }),
  tag("shop", {
    label: "Shop",
    aliases: ["store", "retail shop"],
    parents: ["building"],
    implies: ["building"],
    related: ["market"],
  }),
  tag("skyscraper", {
    label: "Skyscraper",
    aliases: ["high-rise", "tower block"],
    parents: ["building", "city"],
    implies: ["building", "architecture", "city"],
  }),
  tag("temple-building", {
    label: "Temple",
    aliases: ["shrine building", "sanctuary"],
    parents: ["building"],
    implies: ["building", "architecture"],
    related: ["temple-attraction"],
  }),
  tag("tower", {
    label: "Tower",
    aliases: ["spire", "turret"],
    parents: ["building"],
    implies: ["building", "architecture"],
  }),
  tag("warehouse", {
    label: "Warehouse",
    aliases: ["depot", "storage building"],
    parents: ["building"],
    implies: ["building", "architecture", "storage-room"],
  }),
  tag("workshop", {
    label: "Workshop",
    aliases: ["studio", "workroom", "forge", "smithy", "blacksmith shop"],
    parents: ["building"],
    implies: ["building", "crafting-station"],
  }),
];
