import { tag } from "../../tag";

type NamedCity = readonly [id: string, label: string, countryId: string, aliases?: readonly string[]];

const cities: NamedCity[] = [
  ["city-abu-dhabi", "Abu Dhabi", "country-united-arab-emirates"],
  ["city-accra", "Accra", "country-ghana"],
  ["city-addis-ababa", "Addis Ababa", "country-ethiopia"],
  ["city-adelaide", "Adelaide", "country-australia"],
  ["city-alexandria", "Alexandria", "country-egypt"],
  ["city-amsterdam", "Amsterdam", "country-netherlands"],
  ["city-ankara", "Ankara", "country-turkiye"],
  ["city-antwerp", "Antwerp", "country-belgium"],
  ["city-apia", "Apia", "country-samoa"],
  ["city-asuncion", "Asuncion", "country-paraguay"],
  ["city-athens", "Athens", "country-greece"],
  ["city-atlanta", "Atlanta", "country-united-states"],
  ["city-auckland", "Auckland", "country-new-zealand"],
  ["city-austin", "Austin", "country-united-states"],
  ["city-baghdad", "Baghdad", "country-iraq"],
  ["city-baku", "Baku", "country-azerbaijan"],
  ["city-baltimore", "Baltimore", "country-united-states"],
  ["city-bangalore", "Bangalore", "country-india", ["Bengaluru"]],
  ["city-bangkok", "Bangkok", "country-thailand"],
  ["city-barcelona", "Barcelona", "country-spain"],
  ["city-beijing", "Beijing", "country-china"],
  ["city-belfast", "Belfast", "country-united-kingdom"],
  ["city-belgrade", "Belgrade", "country-serbia"],
  ["city-berlin", "Berlin", "country-germany"],
  ["city-bogota", "Bogota", "country-colombia"],
  ["city-bologna", "Bologna", "country-italy"],
  ["city-bordeaux", "Bordeaux", "country-france"],
  ["city-boston", "Boston", "country-united-states"],
  ["city-bratislava", "Bratislava", "country-slovakia"],
  ["city-brighton", "Brighton", "country-united-kingdom"],
  ["city-brisbane", "Brisbane", "country-australia"],
  ["city-bristol", "Bristol", "country-united-kingdom"],
  ["city-brussels", "Brussels", "country-belgium"],
  ["city-bucharest", "Bucharest", "country-romania"],
  ["city-budapest", "Budapest", "country-hungary"],
  ["city-buenos-aires", "Buenos Aires", "country-argentina"],
  ["city-busan", "Busan", "country-south-korea"],
  ["city-cairo", "Cairo", "country-egypt"],
  ["city-calgary", "Calgary", "country-canada"],
  ["city-canberra", "Canberra", "country-australia"],
  ["city-cancun", "Cancun", "country-mexico", ["Cancun, Quintana Roo"]],
  ["city-cape-town", "Cape Town", "country-south-africa"],
  ["city-cardiff", "Cardiff", "country-united-kingdom"],
  ["city-casablanca", "Casablanca", "country-morocco"],
  ["city-charleston", "Charleston", "country-united-states"],
  ["city-charlotte", "Charlotte", "country-united-states"],
  ["city-chengdu", "Chengdu", "country-china"],
  ["city-chiang-mai", "Chiang Mai", "country-thailand"],
  ["city-chicago", "Chicago", "country-united-states"],
  ["city-christchurch", "Christchurch", "country-new-zealand"],
  ["city-cincinnati", "Cincinnati", "country-united-states"],
  ["city-cleveland", "Cleveland", "country-united-states"],
  ["city-cologne", "Cologne", "country-germany", ["Koln"]],
  ["city-colombo", "Colombo", "country-sri-lanka"],
  ["city-columbus", "Columbus", "country-united-states"],
  ["city-copenhagen", "Copenhagen", "country-denmark"],
  ["city-da-nang", "Da Nang", "country-vietnam"],
  ["city-dakar", "Dakar", "country-senegal"],
  ["city-dallas", "Dallas", "country-united-states"],
  ["city-darwin", "Darwin", "country-australia"],
  ["city-delhi", "Delhi", "country-india", ["New Delhi"]],
  ["city-denver", "Denver", "country-united-states"],
  ["city-detroit", "Detroit", "country-united-states"],
  ["city-dhaka", "Dhaka", "country-bangladesh"],
  ["city-doha", "Doha", "country-qatar"],
  ["city-dresden", "Dresden", "country-germany"],
  ["city-dubai", "Dubai", "country-united-arab-emirates"],
  ["city-dublin", "Dublin", "country-ireland"],
  ["city-dusseldorf", "Dusseldorf", "country-germany"],
  ["city-edinburgh", "Edinburgh", "country-united-kingdom"],
  ["city-edmonton", "Edmonton", "country-canada"],
  ["city-fez", "Fez", "country-morocco"],
  ["city-florence", "Florence", "country-italy", ["Firenze"]],
  ["city-frankfurt", "Frankfurt", "country-germany"],
  ["city-fukuoka", "Fukuoka", "country-japan"],
  ["city-galway", "Galway", "country-ireland"],
  ["city-geneva", "Geneva", "country-switzerland"],
  ["city-glasgow", "Glasgow", "country-united-kingdom"],
  ["city-gold-coast", "Gold Coast", "country-australia", ["Gold Coast, Queensland"]],
  ["city-guangzhou", "Guangzhou", "country-china", ["Canton"]],
  ["city-guatemala-city", "Guatemala City", "country-guatemala"],
  ["city-hamburg", "Hamburg", "country-germany"],
  ["city-hanoi", "Hanoi", "country-vietnam"],
  ["city-havana", "Havana", "country-cuba"],
  ["city-helsinki", "Helsinki", "country-finland"],
  ["city-ho-chi-minh-city", "Ho Chi Minh City", "country-vietnam", ["Saigon"]],
  ["city-hobart", "Hobart", "country-australia"],
  ["city-hong-kong", "Hong Kong", "country-china", ["Hong Kong SAR"]],
  ["city-honolulu", "Honolulu", "country-united-states"],
  ["city-houston", "Houston", "country-united-states"],
  ["city-hyderabad", "Hyderabad", "country-india"],
  ["city-incheon", "Incheon", "country-south-korea"],
  ["city-istanbul", "Istanbul", "country-turkiye"],
  ["city-jaipur", "Jaipur", "country-india"],
  ["city-jakarta", "Jakarta", "country-indonesia"],
  ["city-jerusalem", "Jerusalem", "country-israel"],
  ["city-johannesburg", "Johannesburg", "country-south-africa"],
  ["city-kabul", "Kabul", "country-afghanistan"],
  ["city-kathmandu", "Kathmandu", "country-nepal"],
  ["city-kobe", "Kobe", "country-japan"],
  ["city-kolkata", "Kolkata", "country-india", ["Calcutta"]],
  ["city-krakow", "Krakow", "country-poland"],
  ["city-kuala-lumpur", "Kuala Lumpur", "country-malaysia"],
  ["city-kyoto", "Kyoto", "country-japan"],
  ["city-lagos", "Lagos", "country-nigeria"],
  ["city-lahore", "Lahore", "country-pakistan"],
  ["city-las-vegas", "Las Vegas", "country-united-states"],
  ["city-lima", "Lima", "country-peru"],
  ["city-lisbon", "Lisbon", "country-portugal"],
  ["city-liverpool", "Liverpool", "country-united-kingdom"],
  ["city-ljubljana", "Ljubljana", "country-slovenia"],
  ["city-london", "London", "country-united-kingdom"],
  ["city-los-angeles", "Los Angeles", "country-united-states", ["LA"]],
  ["city-luxembourg-city", "Luxembourg City", "country-luxembourg"],
  ["city-lyon", "Lyon", "country-france"],
  ["city-macao", "Macao", "country-china", ["Macau"]],
  ["city-madrid", "Madrid", "country-spain"],
  ["city-manchester", "Manchester", "country-united-kingdom"],
  ["city-manila", "Manila", "country-philippines"],
  ["city-marrakesh", "Marrakesh", "country-morocco", ["Marrakech"]],
  ["city-marseille", "Marseille", "country-france"],
  ["city-medellin", "Medellin", "country-colombia"],
  ["city-melbourne", "Melbourne", "country-australia"],
  ["city-memphis", "Memphis", "country-united-states"],
  ["city-mexico-city", "Mexico City", "country-mexico"],
  ["city-miami", "Miami", "country-united-states"],
  ["city-milan", "Milan", "country-italy", ["Milano"]],
  ["city-minneapolis", "Minneapolis", "country-united-states"],
  ["city-montevideo", "Montevideo", "country-uruguay"],
  ["city-montreal", "Montreal", "country-canada"],
  ["city-moscow", "Moscow", "country-russia"],
  ["city-mumbai", "Mumbai", "country-india", ["Bombay"]],
  ["city-munich", "Munich", "country-germany"],
  ["city-nagoya", "Nagoya", "country-japan"],
  ["city-nairobi", "Nairobi", "country-kenya"],
  ["city-naples", "Naples", "country-italy", ["Napoli"]],
  ["city-nashville", "Nashville", "country-united-states"],
  ["city-new-orleans", "New Orleans", "country-united-states"],
  ["city-new-york-city", "New York City", "country-united-states", ["NYC", "New York"]],
  ["city-newcastle", "Newcastle", "country-united-kingdom"],
  ["city-nice", "Nice", "country-france"],
  ["city-nicosia", "Nicosia", "country-cyprus"],
  ["city-nottingham", "Nottingham", "country-united-kingdom"],
  ["city-okinawa", "Okinawa", "country-japan", ["Naha"]],
  ["city-orlando", "Orlando", "country-united-states"],
  ["city-osaka", "Osaka", "country-japan"],
  ["city-oslo", "Oslo", "country-norway"],
  ["city-ottawa", "Ottawa", "country-canada"],
  ["city-oxford", "Oxford", "country-united-kingdom"],
  ["city-panama-city", "Panama City", "country-panama"],
  ["city-paris", "Paris", "country-france"],
  ["city-perth", "Perth", "country-australia"],
  ["city-philadelphia", "Philadelphia", "country-united-states"],
  ["city-phoenix", "Phoenix", "country-united-states"],
  ["city-phuket", "Phuket", "country-thailand"],
  ["city-portland", "Portland", "country-united-states"],
  ["city-porto", "Porto", "country-portugal"],
  ["city-prague", "Prague", "country-czechia", ["Praha"]],
  ["city-pune", "Pune", "country-india"],
  ["city-quebec-city", "Quebec City", "country-canada"],
  ["city-queenstown", "Queenstown", "country-new-zealand"],
  ["city-reykjavik", "Reykjavik", "country-iceland"],
  ["city-riga", "Riga", "country-latvia"],
  ["city-rio-de-janeiro", "Rio de Janeiro", "country-brazil"],
  ["city-riyadh", "Riyadh", "country-saudi-arabia"],
  ["city-rome", "Rome", "country-italy", ["Roma"]],
  ["city-rotterdam", "Rotterdam", "country-netherlands"],
  ["city-salt-lake-city", "Salt Lake City", "country-united-states"],
  ["city-san-antonio", "San Antonio", "country-united-states"],
  ["city-san-diego", "San Diego", "country-united-states"],
  ["city-san-francisco", "San Francisco", "country-united-states"],
  ["city-san-jose-us", "San Jose", "country-united-states", ["San Jose, California"]],
  ["city-san-jose-costa-rica", "San Jose", "country-costa-rica", ["San Jose, Costa Rica"]],
  ["city-san-juan", "San Juan", "country-united-states", ["San Juan, Puerto Rico"]],
  ["city-san-salvador", "San Salvador", "country-el-salvador"],
  ["city-santa-fe", "Santa Fe", "country-united-states"],
  ["city-santiago", "Santiago", "country-chile"],
  ["city-sao-paulo", "Sao Paulo", "country-brazil"],
  ["city-sapporo", "Sapporo", "country-japan"],
  ["city-savannah", "Savannah", "country-united-states"],
  ["city-seattle", "Seattle", "country-united-states"],
  ["city-seoul", "Seoul", "country-south-korea"],
  ["city-seville", "Seville", "country-spain", ["Sevilla"]],
  ["city-shanghai", "Shanghai", "country-china"],
  ["city-shenzhen", "Shenzhen", "country-china"],
  ["city-siem-reap", "Siem Reap", "country-cambodia"],
  ["city-singapore", "Singapore", "country-singapore"],
  ["city-sofia", "Sofia", "country-bulgaria"],
  ["city-st-louis", "St. Louis", "country-united-states", ["Saint Louis"]],
  ["city-st-petersburg", "St. Petersburg", "country-russia", ["Saint Petersburg"]],
  ["city-stockholm", "Stockholm", "country-sweden"],
  ["city-strasbourg", "Strasbourg", "country-france"],
  ["city-sydney", "Sydney", "country-australia"],
  ["city-taipei", "Taipei", "country-taiwan"],
  ["city-tallinn", "Tallinn", "country-estonia"],
  ["city-tbilisi", "Tbilisi", "country-georgia"],
  ["city-tehran", "Tehran", "country-iran"],
  ["city-tel-aviv", "Tel Aviv", "country-israel"],
  ["city-thessaloniki", "Thessaloniki", "country-greece"],
  ["city-tirana", "Tirana", "country-albania"],
  ["city-tokyo", "Tokyo", "country-japan"],
  ["city-toronto", "Toronto", "country-canada"],
  ["city-toulouse", "Toulouse", "country-france"],
  ["city-tunis", "Tunis", "country-tunisia"],
  ["city-valencia", "Valencia", "country-spain"],
  ["city-valletta", "Valletta", "country-malta"],
  ["city-vancouver", "Vancouver", "country-canada"],
  ["city-venice", "Venice", "country-italy", ["Venezia"]],
  ["city-vienna", "Vienna", "country-austria"],
  ["city-vilnius", "Vilnius", "country-lithuania"],
  ["city-warsaw", "Warsaw", "country-poland"],
  ["city-washington-dc", "Washington, DC", "country-united-states", ["Washington D.C.", "Washington DC"]],
  ["city-wellington", "Wellington", "country-new-zealand"],
  ["city-winnipeg", "Winnipeg", "country-canada"],
  ["city-yokohama", "Yokohama", "country-japan"],
  ["city-zagreb", "Zagreb", "country-croatia"],
  ["city-zurich", "Zurich", "country-switzerland"],
];

export const cityTags = cities.map(([id, label, countryId, aliases]) =>
  aliases
    ? tag(id, { label, aliases: [...aliases], parents: ["city", countryId], implies: ["city", countryId] })
    : tag(id, { label, parents: ["city", countryId], implies: ["city", countryId] }),
);
