import { tag } from "../../tag";

type NamedCountry = readonly [id: string, label: string, aliases?: readonly string[]];

const countries: NamedCountry[] = [
  ["country-afghanistan", "Afghanistan"],
  ["country-albania", "Albania"],
  ["country-algeria", "Algeria"],
  ["country-andorra", "Andorra"],
  ["country-angola", "Angola"],
  ["country-antigua-and-barbuda", "Antigua and Barbuda"],
  ["country-argentina", "Argentina"],
  ["country-armenia", "Armenia"],
  ["country-australia", "Australia"],
  ["country-austria", "Austria"],
  ["country-azerbaijan", "Azerbaijan"],
  ["country-bahamas", "Bahamas", ["The Bahamas"]],
  ["country-bahrain", "Bahrain"],
  ["country-bangladesh", "Bangladesh"],
  ["country-barbados", "Barbados"],
  ["country-belarus", "Belarus"],
  ["country-belgium", "Belgium"],
  ["country-belize", "Belize"],
  ["country-benin", "Benin"],
  ["country-bhutan", "Bhutan"],
  ["country-bolivia", "Bolivia"],
  ["country-bosnia-and-herzegovina", "Bosnia and Herzegovina", ["Bosnia"]],
  ["country-botswana", "Botswana"],
  ["country-brazil", "Brazil"],
  ["country-brunei", "Brunei"],
  ["country-bulgaria", "Bulgaria"],
  ["country-burkina-faso", "Burkina Faso"],
  ["country-burundi", "Burundi"],
  ["country-cabo-verde", "Cabo Verde", ["Cape Verde"]],
  ["country-cambodia", "Cambodia"],
  ["country-cameroon", "Cameroon"],
  ["country-canada", "Canada"],
  ["country-central-african-republic", "Central African Republic"],
  ["country-chad", "Chad"],
  ["country-chile", "Chile"],
  ["country-china", "China"],
  ["country-colombia", "Colombia"],
  ["country-comoros", "Comoros"],
  ["country-costa-rica", "Costa Rica"],
  ["country-cote-divoire", "Cote d'Ivoire", ["Ivory Coast"]],
  ["country-croatia", "Croatia"],
  ["country-cuba", "Cuba"],
  ["country-cyprus", "Cyprus"],
  ["country-czechia", "Czechia", ["Czech Republic"]],
  ["country-democratic-republic-of-the-congo", "Democratic Republic of the Congo", ["DR Congo", "Congo-Kinshasa"]],
  ["country-denmark", "Denmark"],
  ["country-djibouti", "Djibouti"],
  ["country-dominica", "Dominica"],
  ["country-dominican-republic", "Dominican Republic"],
  ["country-ecuador", "Ecuador"],
  ["country-egypt", "Egypt"],
  ["country-el-salvador", "El Salvador"],
  ["country-equatorial-guinea", "Equatorial Guinea"],
  ["country-eritrea", "Eritrea"],
  ["country-estonia", "Estonia"],
  ["country-eswatini", "Eswatini", ["Swaziland"]],
  ["country-ethiopia", "Ethiopia"],
  ["country-fiji", "Fiji"],
  ["country-finland", "Finland"],
  ["country-france", "France"],
  ["country-gabon", "Gabon"],
  ["country-gambia", "Gambia", ["The Gambia"]],
  ["country-georgia", "Georgia"],
  ["country-germany", "Germany"],
  ["country-ghana", "Ghana"],
  ["country-greece", "Greece"],
  ["country-grenada", "Grenada"],
  ["country-guatemala", "Guatemala"],
  ["country-guinea", "Guinea"],
  ["country-guinea-bissau", "Guinea-Bissau"],
  ["country-guyana", "Guyana"],
  ["country-haiti", "Haiti"],
  ["country-honduras", "Honduras"],
  ["country-hungary", "Hungary"],
  ["country-iceland", "Iceland"],
  ["country-india", "India"],
  ["country-indonesia", "Indonesia"],
  ["country-iran", "Iran"],
  ["country-iraq", "Iraq"],
  ["country-ireland", "Ireland"],
  ["country-israel", "Israel"],
  ["country-italy", "Italy"],
  ["country-jamaica", "Jamaica"],
  ["country-japan", "Japan"],
  ["country-jordan", "Jordan"],
  ["country-kazakhstan", "Kazakhstan"],
  ["country-kenya", "Kenya"],
  ["country-kiribati", "Kiribati"],
  ["country-kosovo", "Kosovo"],
  ["country-kuwait", "Kuwait"],
  ["country-kyrgyzstan", "Kyrgyzstan"],
  ["country-laos", "Laos", ["Lao PDR"]],
  ["country-latvia", "Latvia"],
  ["country-lebanon", "Lebanon"],
  ["country-lesotho", "Lesotho"],
  ["country-liberia", "Liberia"],
  ["country-libya", "Libya"],
  ["country-liechtenstein", "Liechtenstein"],
  ["country-lithuania", "Lithuania"],
  ["country-luxembourg", "Luxembourg"],
  ["country-madagascar", "Madagascar"],
  ["country-malawi", "Malawi"],
  ["country-malaysia", "Malaysia"],
  ["country-maldives", "Maldives"],
  ["country-mali", "Mali"],
  ["country-malta", "Malta"],
  ["country-marshall-islands", "Marshall Islands"],
  ["country-mauritania", "Mauritania"],
  ["country-mauritius", "Mauritius"],
  ["country-mexico", "Mexico"],
  ["country-micronesia", "Micronesia", ["Federated States of Micronesia"]],
  ["country-moldova", "Moldova"],
  ["country-monaco", "Monaco"],
  ["country-mongolia", "Mongolia"],
  ["country-montenegro", "Montenegro"],
  ["country-morocco", "Morocco"],
  ["country-mozambique", "Mozambique"],
  ["country-myanmar", "Myanmar", ["Burma"]],
  ["country-namibia", "Namibia"],
  ["country-nauru", "Nauru"],
  ["country-nepal", "Nepal"],
  ["country-netherlands", "Netherlands", ["Holland"]],
  ["country-new-zealand", "New Zealand"],
  ["country-nicaragua", "Nicaragua"],
  ["country-niger", "Niger"],
  ["country-nigeria", "Nigeria"],
  ["country-north-korea", "North Korea", ["DPRK"]],
  ["country-north-macedonia", "North Macedonia"],
  ["country-norway", "Norway"],
  ["country-oman", "Oman"],
  ["country-pakistan", "Pakistan"],
  ["country-palau", "Palau"],
  ["country-palestine", "Palestine"],
  ["country-panama", "Panama"],
  ["country-papua-new-guinea", "Papua New Guinea"],
  ["country-paraguay", "Paraguay"],
  ["country-peru", "Peru"],
  ["country-philippines", "Philippines"],
  ["country-poland", "Poland"],
  ["country-portugal", "Portugal"],
  ["country-qatar", "Qatar"],
  ["country-republic-of-the-congo", "Republic of the Congo", ["Congo", "Congo-Brazzaville"]],
  ["country-romania", "Romania"],
  ["country-russia", "Russia"],
  ["country-rwanda", "Rwanda"],
  ["country-saint-kitts-and-nevis", "Saint Kitts and Nevis"],
  ["country-saint-lucia", "Saint Lucia"],
  ["country-saint-vincent-and-the-grenadines", "Saint Vincent and the Grenadines"],
  ["country-samoa", "Samoa"],
  ["country-san-marino", "San Marino"],
  ["country-sao-tome-and-principe", "Sao Tome and Principe"],
  ["country-saudi-arabia", "Saudi Arabia"],
  ["country-senegal", "Senegal"],
  ["country-serbia", "Serbia"],
  ["country-seychelles", "Seychelles"],
  ["country-sierra-leone", "Sierra Leone"],
  ["country-singapore", "Singapore"],
  ["country-slovakia", "Slovakia"],
  ["country-slovenia", "Slovenia"],
  ["country-solomon-islands", "Solomon Islands"],
  ["country-somalia", "Somalia"],
  ["country-south-africa", "South Africa"],
  ["country-south-korea", "South Korea", ["Republic of Korea"]],
  ["country-south-sudan", "South Sudan"],
  ["country-spain", "Spain"],
  ["country-sri-lanka", "Sri Lanka"],
  ["country-sudan", "Sudan"],
  ["country-suriname", "Suriname"],
  ["country-sweden", "Sweden"],
  ["country-switzerland", "Switzerland"],
  ["country-syria", "Syria"],
  ["country-taiwan", "Taiwan"],
  ["country-tajikistan", "Tajikistan"],
  ["country-tanzania", "Tanzania"],
  ["country-thailand", "Thailand"],
  ["country-timor-leste", "Timor-Leste", ["East Timor"]],
  ["country-togo", "Togo"],
  ["country-tonga", "Tonga"],
  ["country-trinidad-and-tobago", "Trinidad and Tobago"],
  ["country-tunisia", "Tunisia"],
  ["country-turkiye", "Turkiye", ["Turkey"]],
  ["country-turkmenistan", "Turkmenistan"],
  ["country-tuvalu", "Tuvalu"],
  ["country-uganda", "Uganda"],
  ["country-ukraine", "Ukraine"],
  ["country-united-arab-emirates", "United Arab Emirates", ["UAE"]],
  ["country-united-kingdom", "United Kingdom", ["UK", "Great Britain", "Britain"]],
  ["country-united-states", "United States", ["USA", "United States of America", "America"]],
  ["country-uruguay", "Uruguay"],
  ["country-uzbekistan", "Uzbekistan"],
  ["country-vanuatu", "Vanuatu"],
  ["country-vatican-city", "Vatican City", ["Holy See"]],
  ["country-venezuela", "Venezuela"],
  ["country-vietnam", "Vietnam"],
  ["country-yemen", "Yemen"],
  ["country-zambia", "Zambia"],
  ["country-zimbabwe", "Zimbabwe"],
];

export const countryTags = countries.map(([id, label, aliases]) =>
  aliases
    ? tag(id, { label, aliases: [...aliases], parents: ["country"], implies: ["country"] })
    : tag(id, { label, parents: ["country"], implies: ["country"] }),
);
