import { tag } from "../../tag";

type NamedDestination = readonly [
  id: string,
  label: string,
  parents: readonly string[],
  aliases?: readonly string[],
];

const destinations: NamedDestination[] = [
  ["destination-acropolis", "Acropolis", ["landmark", "city-athens", "country-greece"]],
  ["destination-alcatraz-island", "Alcatraz Island", ["landmark", "city-san-francisco", "country-united-states"]],
  ["destination-amalfi-coast", "Amalfi Coast", ["coastal-attraction", "country-italy"]],
  ["destination-angkor-wat", "Angkor Wat", ["temple-attraction", "city-siem-reap", "country-cambodia"]],
  ["destination-arc-de-triomphe", "Arc de Triomphe", ["monument", "city-paris", "country-france"]],
  ["destination-banff-national-park", "Banff National Park", ["national-park", "country-canada"]],
  ["destination-bondi-beach", "Bondi Beach", ["coastal-attraction", "city-sydney", "country-australia"]],
  ["destination-borobudur", "Borobudur", ["temple-attraction", "country-indonesia"]],
  ["destination-bourbon-street", "Bourbon Street", ["landmark", "city-new-orleans", "country-united-states"]],
  ["destination-buckingham-palace", "Buckingham Palace", ["palace", "city-london", "country-united-kingdom"]],
  ["destination-burj-khalifa", "Burj Khalifa", ["landmark", "city-dubai", "country-united-arab-emirates"]],
  ["destination-cancun-hotel-zone", "Cancun Hotel Zone", ["coastal-attraction", "city-cancun", "country-mexico"], ["Zona Hotelera"]],
  ["destination-central-park", "Central Park", ["park", "city-new-york-city", "country-united-states"]],
  ["destination-christ-the-redeemer", "Christ the Redeemer", ["monument", "city-rio-de-janeiro", "country-brazil"]],
  ["destination-colosseum", "Colosseum", ["landmark", "city-rome", "country-italy"]],
  ["destination-disneyland", "Disneyland", ["amusement-park", "city-los-angeles", "country-united-states"], ["Disneyland Resort"]],
  ["destination-disney-world", "Walt Disney World", ["amusement-park", "city-orlando", "country-united-states"], ["Disney World"]],
  ["destination-eiffel-tower", "Eiffel Tower", ["landmark", "city-paris", "country-france"]],
  ["destination-ellis-island", "Ellis Island", ["landmark", "city-new-york-city", "country-united-states"]],
  ["destination-empire-state-building", "Empire State Building", ["landmark", "city-new-york-city", "country-united-states"]],
  ["destination-forbidden-city", "Forbidden City", ["landmark", "city-beijing", "country-china"]],
  ["destination-fushimi-inari-taisha", "Fushimi Inari Taisha", ["temple-attraction", "city-kyoto", "country-japan"]],
  ["destination-gardens-by-the-bay", "Gardens by the Bay", ["botanical-garden", "city-singapore", "country-singapore"]],
  ["destination-giza-pyramids", "Pyramids of Giza", ["landmark", "city-cairo", "country-egypt"], ["Giza Pyramids"]],
  ["destination-golden-gate-bridge", "Golden Gate Bridge", ["landmark", "bridge", "city-san-francisco", "country-united-states"]],
  ["destination-grand-canyon", "Grand Canyon", ["national-park", "country-united-states"]],
  ["destination-grand-palace-bangkok", "Grand Palace", ["palace", "city-bangkok", "country-thailand"], ["Grand Palace Bangkok"]],
  ["destination-great-barrier-reef", "Great Barrier Reef", ["coastal-attraction", "country-australia"]],
  ["destination-great-wall-of-china", "Great Wall of China", ["landmark", "country-china"]],
  ["destination-hagia-sophia", "Hagia Sophia", ["landmark", "city-istanbul", "country-turkiye"]],
  ["destination-hollywood-sign", "Hollywood Sign", ["landmark", "city-los-angeles", "country-united-states"]],
  ["destination-louvre", "Louvre", ["museum", "city-paris", "country-france"], ["The Louvre", "Louvre Museum"]],
  ["destination-machu-picchu", "Machu Picchu", ["landmark", "country-peru"]],
  ["destination-marina-bay-sands", "Marina Bay Sands", ["landmark", "city-singapore", "country-singapore"]],
  ["destination-mount-fuji", "Mount Fuji", ["landmark", "country-japan"]],
  ["destination-mount-rushmore", "Mount Rushmore", ["monument", "country-united-states"]],
  ["destination-niagara-falls", "Niagara Falls", ["landmark", "country-canada", "country-united-states"]],
  ["destination-notre-dame", "Notre-Dame Cathedral", ["cathedral", "city-paris", "country-france"], ["Notre Dame"]],
  ["destination-opera-house-sydney", "Sydney Opera House", ["landmark", "city-sydney", "country-australia"]],
  ["destination-petra", "Petra", ["landmark", "country-jordan"]],
  ["destination-pike-place-market", "Pike Place Market", ["market", "city-seattle", "country-united-states"]],
  ["destination-red-square", "Red Square", ["plaza", "city-moscow", "country-russia"]],
  ["destination-rijksmuseum", "Rijksmuseum", ["museum", "city-amsterdam", "country-netherlands"]],
  ["destination-sagrada-familia", "Sagrada Familia", ["cathedral", "city-barcelona", "country-spain"]],
  ["destination-santorini", "Santorini", ["coastal-attraction", "country-greece"]],
  ["destination-shibuya-crossing", "Shibuya Crossing", ["landmark", "city-tokyo", "country-japan"]],
  ["destination-statue-of-liberty", "Statue of Liberty", ["monument", "city-new-york-city", "country-united-states"]],
  ["destination-stonehenge", "Stonehenge", ["landmark", "country-united-kingdom"]],
  ["destination-surfers-paradise", "Surfers Paradise", ["coastal-attraction", "city-gold-coast", "country-australia"]],
  ["destination-taj-mahal", "Taj Mahal", ["landmark", "country-india"]],
  ["destination-table-mountain", "Table Mountain", ["landmark", "city-cape-town", "country-south-africa"]],
  ["destination-times-square", "Times Square", ["landmark", "city-new-york-city", "country-united-states"]],
  ["destination-tower-bridge", "Tower Bridge", ["bridge", "city-london", "country-united-kingdom"]],
  ["destination-tower-of-london", "Tower of London", ["landmark", "city-london", "country-united-kingdom"]],
  ["destination-trevi-fountain", "Trevi Fountain", ["fountain", "city-rome", "country-italy"]],
  ["destination-uluru", "Uluru", ["landmark", "country-australia"], ["Ayers Rock"]],
  ["destination-universal-orlando", "Universal Orlando Resort", ["amusement-park", "city-orlando", "country-united-states"]],
  ["destination-vatican-museums", "Vatican Museums", ["museum", "country-vatican-city"]],
  ["destination-venice-canals", "Venice Canals", ["coastal-attraction", "city-venice", "country-italy"]],
  ["destination-waikiki", "Waikiki", ["coastal-attraction", "city-honolulu", "country-united-states"]],
  ["destination-yosemite", "Yosemite National Park", ["national-park", "country-united-states"]],
];

export const destinationTags = destinations.map(([id, label, parents, aliases]) =>
  tag(id, {
    label,
    aliases: aliases ? [...aliases] : undefined,
    parents: [...parents],
    implies: ["attraction", ...parents],
  }),
);
