import { tag } from "../../tag";

export const locationTags = [
  tag("alley", {
    label: "Alley",
    aliases: ["alleyway", "lane"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
  }),
  tag("border", {
    label: "Border",
    aliases: ["frontier", "boundary"],
    parents: ["country"],
    implies: ["country"],
  }),
  tag("boulevard", {
    label: "Boulevard",
    aliases: ["avenue", "wide street"],
    parents: ["road", "city"],
    implies: ["road", "city"],
  }),
  tag("capital-city", {
    label: "Capital City",
    aliases: ["capital", "seat of government"],
    parents: ["city", "country"],
    implies: ["city", "country"],
  }),
  tag("city", {
    label: "City",
    aliases: ["urban", "metropolis"],
    parents: ["location"],
    related: ["building", "road", "vehicle"],
  }),
  tag("city-block", {
    label: "City Block",
    aliases: ["block", "urban block"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
  }),
  tag("country", {
    label: "Country",
    aliases: ["nation", "state"],
    parents: ["location"],
    related: ["region", "border"],
  }),
  tag("countryside", {
    label: "Countryside",
    aliases: ["rural area", "country landscape"],
    related: ["village", "farm", "grassland-biome"],
  }),
  tag("county", {
    label: "County",
    aliases: ["shire", "local county"],
    parents: ["region"],
    implies: ["region"],
  }),
  tag("crosswalk", {
    label: "Crosswalk",
    aliases: ["pedestrian crossing", "zebra crossing"],
    parents: ["street"],
    implies: ["street", "road", "city"],
  }),
  tag("desert-country", {
    label: "Desert Country",
    aliases: ["arid country", "desert nation"],
    parents: ["country"],
    implies: ["country", "desert-biome"],
  }),
  tag("district", {
    label: "District",
    aliases: ["neighbourhood", "quarter"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
  }),
  tag("downtown", {
    label: "Downtown",
    aliases: ["city centre", "central business district"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
  }),
  tag("intersection", {
    label: "Intersection",
    aliases: ["crossroads", "junction"],
    parents: ["road"],
    implies: ["road", "city"],
  }),
  tag("island-nation", {
    label: "Island Nation",
    aliases: ["island country", "archipelago nation"],
    parents: ["country"],
    implies: ["country", "coastal-biome"],
  }),
  tag("location", {
    label: "Location",
    aliases: ["place", "geographic location"],
    related: ["environment", "map-location"],
  }),
  tag("map-location", {
    label: "Map Location",
    aliases: ["mapped place", "geographic location"],
    parents: ["location"],
    related: ["country", "region", "city"],
  }),
  tag("plaza", {
    label: "Plaza",
    aliases: ["square", "town square"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
  }),
  tag("province", {
    label: "Province",
    aliases: ["state province", "territory"],
    parents: ["region"],
    implies: ["region", "country"],
  }),
  tag("railway-station", {
    label: "Railway Station",
    aliases: ["train station", "station"],
    parents: ["building", "city"],
    implies: ["building", "city", "transport"],
  }),
  tag("region", {
    label: "Region",
    aliases: ["area", "territory"],
    parents: ["location"],
    related: ["country", "province", "city"],
  }),
  tag("road", {
    label: "Road",
    aliases: ["path", "sidewalk", "trail"],
    related: ["city", "transport"],
  }),
  tag("rural-environment", {
    label: "Rural Environment",
    aliases: ["rural setting", "country setting"],
    related: ["countryside", "farm", "village"],
  }),
  tag("seaside-town", {
    label: "Seaside Town",
    aliases: ["coastal town", "beach town"],
    parents: ["town", "coastal-biome"],
    implies: ["town", "coastal-biome"],
  }),
  tag("skyline", {
    label: "Skyline",
    aliases: ["city skyline", "urban horizon"],
    parents: ["city"],
    implies: ["city", "urban-environment"],
    related: ["skyscraper"],
  }),
  tag("street", {
    label: "Street",
    aliases: ["roadway", "urban street"],
    parents: ["road", "city"],
    implies: ["road", "city"],
  }),
  tag("suburb", {
    label: "Suburb",
    aliases: ["suburban area", "outer neighbourhood"],
    parents: ["city"],
    implies: ["city", "urban-environment", "home"],
  }),
  tag("territory", {
    label: "Territory",
    aliases: ["land area", "controlled region"],
    parents: ["region"],
    implies: ["region"],
  }),
  tag("town", {
    label: "Town",
    aliases: ["small town", "township"],
    parents: ["location"],
    related: ["city", "village", "road"],
  }),
  tag("urban-environment", {
    label: "Urban Environment",
    aliases: ["urban area", "built-up area"],
    related: ["city", "building", "road"],
  }),
  tag("village", {
    label: "Village",
    aliases: ["hamlet", "settlement"],
    parents: ["location"],
    related: ["town", "countryside", "home"],
  }),
  tag("wilderness-area", {
    label: "Wilderness Area",
    aliases: ["wild area", "remote country"],
    parents: ["region"],
    related: ["forest-biome", "mountain-biome", "nature"],
  }),
];
