import { tag } from "../../tag";

export const roomTags = [
  tag("ballroom", {
    label: "Ballroom",
    aliases: ["dance hall"],
    parents: ["room"],
    implies: ["room", "building"],
    related: ["dancing"],
  }),
  tag("bathroom", {
    label: "Bathroom",
    aliases: ["washroom", "restroom"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("bedroom", {
    label: "Bedroom",
    aliases: ["sleeping room"],
    parents: ["room"],
    implies: ["room", "building", "bed"],
  }),
  tag("classroom", {
    label: "Classroom",
    aliases: ["school room"],
    parents: ["room", "school-building"],
    implies: ["room", "building", "education"],
  }),
  tag("closet", {
    label: "Closet",
    aliases: ["wardrobe room", "cupboard"],
    parents: ["storage-room"],
    implies: ["storage-room", "room", "building"],
  }),
  tag("corridor", {
    label: "Corridor",
    aliases: ["passageway", "hall"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("dining-room", {
    label: "Dining Room",
    aliases: ["dining area"],
    parents: ["room", "home"],
    implies: ["room", "building", "home"],
  }),
  tag("hallway", {
    label: "Hallway",
    aliases: ["entrance hall", "hall"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("garage", {
    label: "Garage",
    aliases: ["carport"],
    parents: ["room", "home"],
    implies: ["room", "building", "home", "vehicle"],
  }),
  tag("kitchen", {
    label: "Kitchen",
    aliases: ["cookhouse"],
    parents: ["room", "home"],
    implies: ["room", "building", "home", "cooking"],
  }),
  tag("laundry-room", {
    label: "Laundry Room",
    aliases: ["utility room"],
    parents: ["room", "home"],
    implies: ["room", "building", "home"],
  }),
  tag("laboratory", {
    label: "Laboratory",
    aliases: ["lab", "science room"],
    parents: ["room"],
    implies: ["room", "building"],
    related: ["science"],
  }),
  tag("library-room", {
    label: "Library Room",
    aliases: ["reading room", "book room"],
    parents: ["room"],
    implies: ["room", "building", "book"],
  }),
  tag("living-room", {
    label: "Living Room",
    aliases: ["lounge", "sitting room"],
    parents: ["room", "home"],
    implies: ["room", "building", "home"],
  }),
  tag("lobby", {
    label: "Lobby",
    aliases: ["foyer", "reception area", "entryway", "entrance"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("nursery-room", {
    label: "Nursery",
    aliases: ["baby room", "child room"],
    parents: ["bedroom"],
    implies: ["bedroom", "room", "home"],
  }),
  tag("office", {
    label: "Office",
    aliases: ["workspace", "study office"],
    parents: ["room"],
    implies: ["room", "building"],
    related: ["work"],
  }),
  tag("room", {
    label: "Room",
    aliases: ["interior", "indoors", "interior space"],
    parents: ["building"],
    implies: ["building", "architecture"],
  }),
  tag("storage-room", {
    label: "Storage Room",
    aliases: ["storeroom", "supply room", "stockroom", "back room", "backroom"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("study", {
    label: "Study",
    aliases: ["home office", "den"],
    parents: ["room", "home"],
    implies: ["room", "home", "building"],
  }),
  tag("throne-room", {
    label: "Throne Room",
    aliases: ["royal hall", "audience chamber"],
    parents: ["room", "palace"],
    implies: ["room", "building"],
  }),
  tag("waiting-room", {
    label: "Waiting Room",
    aliases: ["waiting area"],
    parents: ["room"],
    implies: ["room", "building"],
  }),
  tag("attic", {
    label: "Attic",
    aliases: ["loft", "roof space"],
    parents: ["room", "home"],
    implies: ["room", "home", "building"],
  }),
  tag("basement", {
    label: "Basement",
    aliases: ["cellar", "undercroft"],
    parents: ["room", "home"],
    implies: ["room", "home", "building"],
  }),
];
