import { tag } from "../../tag";

export const humanoidTags = [
  tag("android", {
    label: "Android",
    aliases: ["synthetic person", "robot person"],
    parents: ["humanoid"],
    implies: ["humanoid", "person"],
    related: ["machine", "robot"],
  }),
  tag("angel", {
    label: "Angel",
    aliases: ["celestial", "divine being"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
  }),
  tag("centaur", {
    label: "Centaur",
    aliases: ["horse person", "horse humanoid"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
    related: ["horse"],
  }),
  tag("character", {
    label: "Character",
    aliases: ["npc", "avatar", "hero", "protagonist"],
    parents: ["person"],
    implies: ["person"],
  }),
  tag("demon", {
    label: "Demon",
    aliases: ["fiend", "infernal"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
  }),
  tag("dwarf", {
    label: "Dwarf",
    aliases: ["dwarven", "dwarvish"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("elf", {
    label: "Elf",
    aliases: ["elven", "elvish"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("ent", {
    label: "Ent",
    aliases: ["tree person", "treefolk", "treant"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person", "plant"],
    related: ["tree", "wood"],
  }),
  tag("fairy", {
    label: "Fairy",
    aliases: ["fae", "faerie", "sprite"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
  }),
  tag("fantasy-people", {
    label: "Fantasy People",
    aliases: ["fantasy race", "fantasy species"],
    parents: ["humanoid"],
    implies: ["humanoid", "person"],
  }),
  tag("giant", {
    label: "Giant",
    aliases: ["titan", "large humanoid"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
  }),
  tag("goblin", {
    label: "Goblin",
    aliases: ["goblinkin"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("halfling", {
    label: "Halfling",
    aliases: ["hobbit", "smallfolk"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("human", {
    label: "Human",
    aliases: ["humans", "human being"],
    parents: ["person"],
    implies: ["person"],
  }),
  tag("humanoid", {
    label: "Humanoid",
    aliases: ["humanlike", "human-like", "person-shaped"],
    parents: ["person"],
    implies: ["person"],
  }),
  tag("merfolk", {
    label: "Merfolk",
    aliases: ["mermaid", "merman", "sea person"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
    related: ["fish", "water"],
  }),
  tag("mythic-humanoid", {
    label: "Mythic Humanoid",
    aliases: ["mythical person", "legendary humanoid"],
    parents: ["humanoid"],
    implies: ["humanoid", "person"],
  }),
  tag("orc", {
    label: "Orc",
    aliases: ["ork", "orcish"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("person", {
    label: "Person",
    aliases: ["people", "sentient being"],
  }),
  tag("player", {
    label: "Player",
    aliases: ["playable character", "main character"],
    parents: ["character"],
    implies: ["character", "person"],
  }),
  tag("satyr", {
    label: "Satyr",
    aliases: ["faun", "goat person"],
    parents: ["mythic-humanoid"],
    implies: ["mythic-humanoid", "humanoid", "person"],
    related: ["goat"],
  }),
  tag("tiefling", {
    label: "Tiefling",
    aliases: ["horned humanoid", "infernal humanoid"],
    parents: ["fantasy-people"],
    implies: ["fantasy-people", "humanoid", "person"],
  }),
  tag("undead-humanoid", {
    label: "Undead Humanoid",
    aliases: ["undead person", "zombie", "skeleton"],
    parents: ["humanoid"],
    implies: ["humanoid", "person"],
    related: ["bone"],
  }),
];
