import { tag } from "../../tag";

export const roleTags = [
  tag("alchemy", {
    label: "Alchemist",
    aliases: ["alchemy", "brewing", "potion maker"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["bottle", "glass", "herb"],
  }),
  tag("architectural-design", {
    label: "Architect",
    aliases: ["architecture", "architectural design", "building designer"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["building", "structure"],
  }),
  tag("crafting", {
    label: "Crafter",
    aliases: ["crafting", "maker", "artisan"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["crafting-station", "tool", "material"],
  }),
  tag("engineering", {
    label: "Engineer",
    aliases: ["engineering", "mechanical designer"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["machine", "tool", "metal"],
  }),
  tag("farming", {
    label: "Farmer",
    aliases: ["farming", "agriculture", "cultivation"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["farm", "plant", "crop", "vegetable"],
  }),
  tag("fishing", {
    label: "Fisher",
    aliases: ["fishing", "angler"],
    parents: ["role"],
    implies: ["role", "person"],
  }),
  tag("healing", {
    label: "Healer",
    aliases: ["healing", "medic", "doctor", "first aider"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["health"],
  }),
  tag("metalworking", {
    label: "Metalworker",
    aliases: ["metalworking", "smith", "blacksmith"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["metal", "anvil", "furnace"],
  }),
  tag("mining", {
    label: "Miner",
    aliases: ["mining", "mine worker"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["rock", "stone", "pickaxe"],
  }),
  tag("role", {
    label: "Role",
    aliases: ["profession", "occupation", "job", "trade"],
    parents: ["person"],
    implies: ["person"],
  }),
  tag("tailoring", {
    label: "Tailor",
    aliases: ["tailoring", "sewing", "textile worker"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["fabric", "clothing"],
  }),
  tag("teaching", {
    label: "Teacher",
    aliases: ["teaching", "instructor", "educator"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["book", "school"],
  }),
  tag("trading", {
    label: "Trader",
    aliases: ["trading", "merchant", "commerce"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["market", "shop"],
  }),
  tag("woodcutting", {
    label: "Woodcutter",
    aliases: ["woodcutting", "wood cutter", "logger"],
    parents: ["role"],
    implies: ["role", "person"],
    related: ["wood", "tree", "hatchet"],
  }),
];
