import { tag } from "../../../tag";

export const mammalTags = [
  tag("anteater", {
    label: "Anteater",
    aliases: ["aardvark"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("ape", {
    label: "Ape",
    aliases: ["gorilla", "chimpanzee", "orangutan", "gibbon"],
    parents: ["primate"],
    implies: ["primate", "mammal", "animal"],
  }),
  tag("armadillo", {
    label: "Armadillo",
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("bat", {
    label: "Bat",
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("bear", {
    label: "Bear",
    aliases: ["grizzly", "polar bear", "black bear", "panda"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("big-cat", {
    label: "Big Cat",
    aliases: ["lion", "tiger", "leopard", "jaguar", "panther", "cheetah", "cougar", "lynx"],
    parents: ["cat"],
    implies: ["cat", "mammal", "animal"],
  }),
  tag("camel", {
    label: "Camel",
    aliases: ["llama", "alpaca"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal"],
  }),
  tag("cat", {
    label: "Cat",
    aliases: ["kitten", "feline"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("cow", {
    label: "Cow",
    aliases: ["cattle", "bull", "calf", "ox", "bison", "buffalo", "yak"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal", "farm"],
  }),
  tag("deer", {
    label: "Deer",
    aliases: ["stag", "doe", "elk", "moose", "reindeer", "caribou"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("dog", {
    label: "Dog",
    aliases: ["puppy", "canine"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("dolphin", {
    label: "Dolphin",
    aliases: ["porpoise"],
    parents: ["mammal", "water"],
    implies: ["mammal", "animal", "water"],
  }),
  tag("elephant", {
    label: "Elephant",
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("farm-animal", {
    label: "Farm Animal",
    aliases: ["livestock", "barnyard"],
    parents: ["animal"],
    implies: ["animal", "farm"],
  }),
  tag("giraffe", {
    label: "Giraffe",
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("goat", {
    label: "Goat",
    aliases: ["kid", "ibex"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal", "farm"],
  }),
  tag("hippopotamus", {
    label: "Hippopotamus",
    aliases: ["hippo"],
    parents: ["mammal"],
    implies: ["mammal", "animal", "water"],
  }),
  tag("horse", {
    label: "Horse",
    aliases: ["pony", "donkey", "mule", "zebra"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal", "farm"],
  }),
  tag("kangaroo", {
    label: "Kangaroo",
    aliases: ["wallaby", "marsupial"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("koala", {
    label: "Koala",
    aliases: ["marsupial"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("mammal", {
    label: "Mammal",
    parents: ["animal"],
    implies: ["animal"],
  }),
  tag("monkey", {
    label: "Monkey",
    aliases: ["macaque", "baboon"],
    parents: ["primate"],
    implies: ["primate", "mammal", "animal"],
  }),
  tag("pig", {
    label: "Pig",
    aliases: ["hog", "piglet", "boar"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal", "farm"],
  }),
  tag("primate", {
    label: "Primate",
    aliases: ["monkey", "ape"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("rabbit", {
    label: "Rabbit",
    aliases: ["bunny", "hare"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("raccoon", {
    label: "Raccoon",
    aliases: ["opossum", "possum", "skunk", "badger", "otter", "weasel", "ferret", "marten", "mongoose", "meerkat"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("rhinoceros", {
    label: "Rhinoceros",
    aliases: ["rhino"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("rodent", {
    label: "Rodent",
    aliases: ["mouse", "rat", "squirrel", "beaver", "porcupine", "hamster", "guinea pig"],
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("seal", {
    label: "Seal",
    aliases: ["sea lion", "walrus"],
    parents: ["mammal", "water"],
    implies: ["mammal", "animal", "water"],
  }),
  tag("sheep", {
    label: "Sheep",
    aliases: ["lamb", "ram"],
    parents: ["mammal", "farm-animal"],
    implies: ["mammal", "farm-animal", "animal", "farm", "wool"],
  }),
  tag("sloth", {
    label: "Sloth",
    parents: ["mammal"],
    implies: ["mammal", "animal"],
  }),
  tag("whale", {
    label: "Whale",
    aliases: ["orca", "humpback", "sperm whale", "beluga"],
    parents: ["mammal", "water"],
    implies: ["mammal", "animal", "water"],
  }),
  tag("wild-dog", {
    label: "Wild Dog",
    aliases: ["wolf", "fox", "coyote", "jackal", "dingo"],
    parents: ["dog"],
    implies: ["dog", "mammal", "animal"],
  }),
];
