export const MAX_IMAGE_AUTO_TAGS = 5;

export const allowedImageAutoTagIds = new Set([
  "animal",
  "bird",
  "cat",
  "dog",
  "horse",
  "fish",
  "insect",
  "reptile",
  "person",
  "food",
  "fruit",
  "vegetable",
  "dessert",
  "bread",
  "drink",
  "flower",
  "tree",
  "grass",
  "forest",
  "plant-life",
  "beach",
  "ocean",
  "river",
  "lake",
  "waterfall",
  "mountain",
  "hill",
  "desert",
  "snow",
  "rain",
  "sky",
  "sunset",
  "sunrise",
  "indoors",
  "outdoors",
  "room",
  "shop",
  "storage",
  "warehouse",
  "building",
  "house",
  "apartment",
  "castle",
  "bridge",
  "road",
  "street",
  "path",
  "city",
  "transport",
  "paper-document",
  "book",
  "map",
  "letter",
  "sign",
  "technology",
  "furniture",
  "tool",
  "weapon",
  "clothing",
  "bag",
  "toy",
  "artwork",
  "logo",
  "crowd",
  "music",
  "musical-instrument",
  "party",
  "ceremony",
  "sport",
]);

export const blockedImageAutoTagIds = new Set([
  "activity",
  "architecture",
  "country",
  "event",
  "landmark",
  "location",
  "meal",
  "place",
  "role",
  "style",
]);

export const imageAutoTagMinScores: Record<string, number> = {
  animal: 0.2,
  apartment: 0.24,
  artwork: 0.25,
  bag: 0.22,
  beach: 0.22,
  bird: 0.24,
  book: 0.24,
  bread: 0.22,
  bridge: 0.23,
  building: 0.2,
  castle: 0.24,
  cat: 0.24,
  ceremony: 0.28,
  city: 0.24,
  clothing: 0.22,
  crowd: 0.22,
  desert: 0.22,
  dessert: 0.22,
  dog: 0.24,
  drink: 0.22,
  fish: 0.24,
  flower: 0.22,
  food: 0.2,
  forest: 0.22,
  fruit: 0.2,
  furniture: 0.22,
  grass: 0.22,
  hill: 0.22,
  horse: 0.24,
  house: 0.23,
  indoors: 0.2,
  insect: 0.24,
  lake: 0.22,
  letter: 0.24,
  logo: 0.28,
  map: 0.24,
  mountain: 0.22,
  music: 0.3,
  "musical-instrument": 0.24,
  ocean: 0.22,
  outdoors: 0.2,
  "paper-document": 0.24,
  party: 0.28,
  path: 0.22,
  person: 0.2,
  "plant-life": 0.22,
  rain: 0.25,
  reptile: 0.24,
  river: 0.22,
  road: 0.22,
  room: 0.21,
  shop: 0.23,
  sign: 0.24,
  sky: 0.22,
  snow: 0.22,
  sport: 0.26,
  storage: 0.24,
  street: 0.22,
  sunrise: 0.25,
  sunset: 0.25,
  technology: 0.22,
  tool: 0.22,
  toy: 0.22,
  transport: 0.22,
  tree: 0.22,
  vegetable: 0.2,
  warehouse: 0.24,
  waterfall: 0.24,
  weapon: 0.24,
};

export const DEFAULT_IMAGE_AUTO_TAG_MIN_SCORE = 0.2;
export const IMAGE_AUTO_TAG_SECONDARY_RATIO = 0.82;

export const imageAutoTagSuppressions: Record<string, string[]> = {
  apartment: ["building", "indoors"],
  artwork: [],
  bag: [],
  beach: ["outdoors"],
  bird: ["animal"],
  book: ["paper-document"],
  bread: ["food"],
  bridge: ["building"],
  castle: ["building"],
  cat: ["animal"],
  city: ["outdoors"],
  crowd: ["person"],
  desert: ["outdoors"],
  dessert: ["food"],
  dog: ["animal"],
  drink: ["food"],
  fish: ["animal"],
  flower: ["plant-life"],
  forest: ["plant-life", "outdoors"],
  fruit: ["food"],
  grass: ["plant-life"],
  hill: ["outdoors"],
  horse: ["animal"],
  house: ["building", "indoors"],
  insect: ["animal"],
  lake: ["outdoors"],
  letter: ["paper-document"],
  logo: [],
  map: ["paper-document"],
  mountain: ["outdoors"],
  "musical-instrument": ["music"],
  ocean: ["outdoors"],
  party: ["crowd"],
  path: ["outdoors"],
  rain: ["outdoors"],
  reptile: ["animal"],
  river: ["outdoors"],
  road: ["outdoors"],
  room: ["indoors", "building"],
  shop: ["building", "indoors"],
  sign: [],
  sky: ["outdoors"],
  snow: ["outdoors"],
  sport: [],
  storage: ["indoors"],
  street: ["outdoors"],
  sunrise: ["sky", "outdoors"],
  sunset: ["sky", "outdoors"],
  transport: [],
  tree: ["plant-life"],
  vegetable: ["food"],
  warehouse: ["building", "indoors", "storage"],
  waterfall: ["outdoors"],
};
