import { tag } from "../../tag";

export const professionTags = [
  tag("alchemy", {
    label: "Alchemy",
    aliases: ["brewing", "potion making"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["bottle", "glass", "herb"],
  }),
  tag("architectural-design", {
    label: "Architectural Design",
    aliases: ["architecture", "architectural design", "building design"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["building", "structure"],
  }),
  tag("crafting", {
    label: "Crafting",
    aliases: ["making", "workbench"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["crafting-station", "tool", "material"],
  }),
  tag("engineering", {
    label: "Engineering",
    aliases: ["engineer", "mechanical design"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["machine", "tool", "metal"],
  }),
  tag("farming", {
    label: "Farming",
    aliases: ["agriculture", "cultivation"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["farm", "plant", "crop", "vegetable"],
  }),
  tag("fishing", {
    label: "Fishing",
    aliases: ["angling"],
    parents: ["profession"],
    implies: ["profession", "activity"],
  }),
  tag("healing", {
    label: "Healing",
    aliases: ["medicine", "medical", "first aid"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["health"],
  }),
  tag("metalworking", {
    label: "Metalworking",
    aliases: ["smithing", "blacksmithing"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["metal", "anvil", "furnace"],
  }),
  tag("mining", {
    label: "Mining",
    aliases: ["mine"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["rock", "stone", "pickaxe"],
  }),
  tag("profession", {
    label: "Profession",
    aliases: ["occupation", "job", "trade"],
    parents: ["activity"],
    implies: ["activity"],
  }),
  tag("tailoring", {
    label: "Tailoring",
    aliases: ["sewing", "textile work"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["fabric", "clothing"],
  }),
  tag("teaching", {
    label: "Teaching",
    aliases: ["instruction", "training", "education"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["book", "school"],
  }),
  tag("trading", {
    label: "Trading",
    aliases: ["merchant", "commerce", "barter"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["market", "shop"],
  }),
  tag("woodcutting", {
    label: "Woodcutting",
    aliases: ["wood cutting", "chopping"],
    parents: ["profession"],
    implies: ["profession", "activity"],
    related: ["wood", "tree", "hatchet"],
  }),
];
