import { tag } from "../../tag";

export const birdTags = [
  tag("bird", {
    label: "Bird",
    aliases: ["avian", "fowl"],
    parents: ["animal"],
    implies: ["animal"],
  }),
  tag("chicken", {
    label: "Chicken",
    aliases: ["hen", "rooster", "chick"],
    parents: ["bird", "farm-animal"],
    implies: ["bird", "farm-animal", "animal"],
    matches: ["bird", "farm-animal"],
    related: ["egg", "feather", "farm"],
  }),
  tag("crow", {
    label: "Crow",
    aliases: ["raven"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("duck", {
    label: "Duck",
    aliases: ["duckling"],
    parents: ["bird", "farm-animal", "water"],
    implies: ["bird", "farm-animal", "animal", "water"],
    matches: ["bird", "farm-animal"],
  }),
  tag("eagle", {
    label: "Eagle",
    aliases: ["hawk", "falcon", "vulture", "condor", "raptor"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("goose", {
    label: "Goose",
    aliases: ["gosling", "geese"],
    parents: ["bird", "farm-animal", "water"],
    implies: ["bird", "farm-animal", "animal", "water"],
    matches: ["bird", "farm-animal"],
  }),
  tag("ostrich", {
    label: "Ostrich",
    aliases: ["emu", "cassowary"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("owl", {
    label: "Owl",
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("parrot", {
    label: "Parrot",
    aliases: ["macaw", "cockatoo", "budgie"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("penguin", {
    label: "Penguin",
    parents: ["bird", "water"],
    implies: ["bird", "animal", "water"],
    matches: ["bird"],
  }),
  tag("pigeon", {
    label: "Pigeon",
    aliases: ["dove"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("seabird", {
    label: "Seabird",
    aliases: ["gull", "pelican", "albatross", "puffin"],
    parents: ["bird", "water"],
    implies: ["bird", "animal", "water"],
    matches: ["bird"],
  }),
  tag("songbird", {
    label: "Songbird",
    aliases: ["sparrow", "robin", "finch", "swallow", "blackbird", "bluebird"],
    parents: ["bird"],
    implies: ["bird", "animal"],
    matches: ["bird"],
  }),
  tag("turkey", {
    label: "Turkey",
    parents: ["bird", "farm-animal"],
    implies: ["bird", "farm-animal", "animal"],
    matches: ["bird", "farm-animal"],
  }),
  tag("wading-bird", {
    label: "Wading Bird",
    aliases: ["heron", "egret", "crane", "stork", "flamingo"],
    parents: ["bird", "water"],
    implies: ["bird", "animal", "water"],
    matches: ["bird"],
  }),
];
