import { tag } from "../../tag";

export const foodTags = [
  tag("allergen", {
    label: "Allergen",
    aliases: ["food allergy", "intolerance"],
    related: ["food", "ingredient"],
  }),
  tag("baked-good", {
    label: "Baked Good",
    aliases: ["baked goods", "bakery item"],
    parents: ["food"],
    implies: ["food", "baking"],
  }),
  tag("baking", {
    label: "Baking",
    aliases: ["bake", "oven cooking"],
    parents: ["cooking"],
    implies: ["cooking"],
  }),
  tag("berry", {
    label: "Berry",
    aliases: ["berries"],
    parents: ["fruit"],
    implies: ["fruit", "food", "ingredient"],
  }),
  tag("calories", {
    label: "Calories",
    aliases: ["energy", "kilocalories"],
    related: ["nutrition", "portion"],
  }),
  tag("carbohydrates", {
    label: "Carbohydrates",
    aliases: ["carbs", "starch", "sugar"],
    parents: ["nutrition"],
    implies: ["nutrition"],
  }),
  tag("cooking", {
    label: "Cooking",
    aliases: ["cookery", "kitchen work"],
    related: ["food", "ingredient", "crafting-station"],
  }),
  tag("dairy", {
    label: "Dairy",
    aliases: ["milk products"],
    parents: ["perishable", "ingredient"],
    implies: ["perishable", "food", "ingredient"],
  }),
  tag("diet", {
    label: "Diet",
    aliases: ["eating pattern", "food plan"],
    related: ["nutrition", "food", "fasting"],
  }),
  tag("drink", {
    label: "Drink",
    aliases: ["beverage"],
    parents: ["food"],
    implies: ["food", "hydration"],
  }),
  tag("eating", {
    label: "Eating",
    aliases: ["dining", "consumption"],
    related: ["food", "meal"],
  }),
  tag("fasting", {
    label: "Fasting",
    aliases: ["not eating", "intermittent fasting"],
    related: ["diet", "eating"],
  }),
  tag("fat", {
    label: "Fat",
    aliases: ["dietary fat", "lipids"],
    parents: ["nutrition"],
    implies: ["nutrition"],
  }),
  tag("fibre", {
    label: "Fibre",
    aliases: ["fiber", "dietary fibre", "roughage"],
    parents: ["nutrition"],
    implies: ["nutrition"],
  }),
  tag("food", {
    label: "Food",
    aliases: ["edible", "meal", "cuisine"],
  }),
  tag("fruit", {
    label: "Fruit",
    aliases: ["produce"],
    parents: ["perishable", "ingredient"],
    implies: ["perishable", "food", "ingredient"],
  }),
  tag("household-grocery", {
    label: "Household Grocery",
    aliases: ["household supplies"],
    parents: ["non-perishable"],
    related: ["pantry", "food-storage"],
  }),
  tag("hydration", {
    label: "Hydration",
    aliases: ["fluid intake", "water intake"],
    related: ["nutrition", "drink"],
  }),
  tag("ingredient", {
    label: "Ingredient",
    aliases: ["component", "raw ingredient"],
    parents: ["food"],
    implies: ["food"],
  }),
  tag("meat", {
    label: "Meat",
    aliases: ["red meat", "animal protein"],
    parents: ["perishable", "ingredient"],
    implies: ["perishable", "food", "ingredient", "protein"],
  }),
  tag("non-perishable", {
    label: "Non-Perishable",
    aliases: ["shelf stable", "long shelf life"],
    related: ["food", "food-storage", "pantry"],
  }),
  tag("nutrition", {
    label: "Nutrition",
    aliases: ["nutritional value", "dietary value"],
    related: ["food", "calories", "protein"],
  }),
  tag("pantry", {
    label: "Pantry",
    aliases: ["dry goods", "cupboard food"],
    parents: ["non-perishable", "ingredient"],
    implies: ["non-perishable", "food", "ingredient"],
  }),
  tag("perishable", {
    label: "Perishable",
    aliases: ["fresh", "short shelf life"],
    related: ["food", "food-storage"],
  }),
  tag("portion", {
    label: "Portion",
    aliases: ["serving", "helping"],
    related: ["meal", "calories"],
  }),
  tag("poultry", {
    label: "Poultry",
    aliases: ["white meat"],
    parents: ["meat"],
    implies: ["meat", "perishable", "food", "ingredient", "protein"],
  }),
  tag("preserve", {
    label: "Preserve",
    aliases: ["preservation", "canning"],
    related: ["food-storage", "non-perishable"],
  }),
  tag("preserved-food", {
    label: "Preserved Food",
    aliases: ["preserves"],
    parents: ["non-perishable"],
    implies: ["non-perishable", "food", "preserve"],
  }),
  tag("protein", {
    label: "Protein",
    aliases: ["dietary protein", "macronutrient"],
    parents: ["nutrition"],
    implies: ["nutrition"],
  }),
  tag("recipe", {
    label: "Recipe",
    aliases: ["instructions", "formula"],
    related: ["cooking", "ingredient", "meal"],
  }),
  tag("sauce", {
    label: "Sauce",
    aliases: ["condiment"],
    parents: ["preserved-food"],
    implies: ["preserved-food", "food", "ingredient"],
  }),
  tag("savoury-food", {
    label: "Savoury Food",
    aliases: ["savory food", "salty food"],
    parents: ["food"],
    implies: ["food"],
  }),
  tag("seafood", {
    label: "Seafood",
    aliases: ["fish meat", "shellfish"],
    parents: ["perishable", "ingredient"],
    implies: ["perishable", "food", "ingredient", "protein", "fish"],
  }),
  tag("snack", {
    label: "Snack",
    aliases: ["snack food"],
    parents: ["food"],
    implies: ["food"],
  }),
  tag("spice", {
    label: "Spice",
    aliases: ["seasoning"],
    parents: ["ingredient", "non-perishable"],
    implies: ["ingredient", "food", "non-perishable"],
  }),
  tag("food-storage", {
    label: "Storage",
    aliases: ["food storage", "keeping"],
    related: ["perishable", "non-perishable", "preserve"],
  }),
  tag("sweet-food", {
    label: "Sweet Food",
    aliases: ["sweets", "sweet treat"],
    parents: ["food"],
    implies: ["food"],
  }),
  tag("vegetable", {
    label: "Vegetable",
    aliases: ["veg", "produce"],
    parents: ["perishable", "ingredient"],
    implies: ["perishable", "food", "ingredient"],
  }),
];
