import { tag } from "../../tag";

export const mealTags = [
  tag("bangers-and-mash", {
    label: "Bangers and Mash",
    aliases: ["sausages and mash"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("beef-bourguignon", {
    label: "Beef Bourguignon",
    aliases: ["boeuf bourguignon"],
    parents: ["main-course", "stew"],
    implies: ["main-course", "meal", "stew", "savoury-food", "food"],
    related: ["country-france"],
  }),
  tag("bibimbap", {
    label: "Bibimbap",
    parents: ["cooked-rice", "main-course"],
    implies: ["cooked-rice", "main-course", "meal", "savoury-food", "food"],
    related: ["country-south-korea"],
  }),
  tag("bolognaise", {
    label: "Bolognaise",
    aliases: ["bolognese", "spaghetti bolognese"],
    parents: ["cooked-pasta", "main-course"],
    implies: ["cooked-pasta", "main-course", "meal", "savoury-food", "food"],
    related: ["country-italy"],
  }),
  tag("butter-chicken", {
    label: "Butter Chicken",
    aliases: ["murgh makhani"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-india"],
  }),
  tag("chicken-parmigiana", {
    label: "Chicken Parmigiana",
    aliases: ["chicken parma", "chicken parmi"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-australia", "country-italy"],
  }),
  tag("chilli-con-carne", {
    label: "Chilli Con Carne",
    aliases: ["chili con carne"],
    parents: ["main-course", "stew"],
    implies: ["main-course", "meal", "stew", "savoury-food", "food"],
    related: ["country-mexico", "country-united-states"],
  }),
  tag("cottage-pie", {
    label: "Cottage Pie",
    parents: ["main-course", "savoury-pie"],
    implies: ["main-course", "meal", "savoury-pie", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("fish-and-chips", {
    label: "Fish and Chips",
    aliases: ["fish & chips"],
    parents: ["main-course", "meal"],
    implies: ["fries", "main-course", "meal", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("fried-chicken-meal", {
    label: "Fried Chicken Meal",
    aliases: ["fried chicken dinner"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-united-states"],
  }),
  tag("full-english-breakfast", {
    label: "Full English Breakfast",
    aliases: ["fry up"],
    parents: ["breakfast", "main-course"],
    implies: ["breakfast", "main-course", "meal", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("jollof-rice", {
    label: "Jollof Rice",
    parents: ["cooked-rice", "main-course"],
    implies: ["cooked-rice", "main-course", "meal", "savoury-food", "food"],
    related: ["country-ghana", "country-nigeria"],
  }),
  tag("katsu-curry", {
    label: "Katsu Curry",
    aliases: ["japanese curry"],
    parents: ["cooked-rice", "main-course"],
    implies: ["cooked-rice", "main-course", "meal", "savoury-food", "food"],
    related: ["country-japan"],
  }),
  tag("lasagne-meal", {
    label: "Lasagne Meal",
    aliases: ["lasagna dinner", "lasagne dinner"],
    parents: ["cooked-pasta", "main-course"],
    implies: ["cooked-pasta", "lasagne", "main-course", "meal", "savoury-food", "food"],
    related: ["country-italy"],
  }),
  tag("mac-and-cheese", {
    label: "Mac and Cheese",
    aliases: ["macaroni and cheese"],
    parents: ["cooked-pasta", "main-course"],
    implies: ["cooked-pasta", "main-course", "meal", "savoury-food", "food"],
    related: ["country-united-states"],
  }),
  tag("moussaka", {
    label: "Moussaka",
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-greece"],
  }),
  tag("paella", {
    label: "Paella",
    parents: ["cooked-rice", "main-course"],
    implies: ["cooked-rice", "main-course", "meal", "savoury-food", "food"],
    related: ["country-spain"],
  }),
  tag("pad-thai", {
    label: "Pad Thai",
    parents: ["cooked-noodles", "main-course"],
    implies: ["cooked-noodles", "main-course", "meal", "savoury-food", "food"],
    related: ["country-thailand"],
  }),
  tag("pho", {
    label: "Pho",
    parents: ["main-course", "soup"],
    implies: ["main-course", "meal", "soup", "savoury-food", "food"],
    related: ["country-vietnam"],
  }),
  tag("risotto", {
    label: "Risotto",
    parents: ["cooked-rice", "main-course"],
    implies: ["cooked-rice", "main-course", "meal", "savoury-food", "food"],
    related: ["country-italy"],
  }),
  tag("roast-dinner", {
    label: "Roast Dinner",
    aliases: ["Sunday roast"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("shepherds-pie", {
    label: "Shepherds Pie",
    aliases: ["shepherd's pie"],
    parents: ["main-course", "savoury-pie"],
    implies: ["main-course", "meal", "savoury-pie", "savoury-food", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("spaghetti-carbonara", {
    label: "Spaghetti Carbonara",
    aliases: ["carbonara"],
    parents: ["cooked-pasta", "main-course"],
    implies: ["cooked-pasta", "main-course", "meal", "savoury-food", "food"],
    related: ["country-italy"],
  }),
  tag("sushi-platter", {
    label: "Sushi Platter",
    parents: ["main-course", "sushi"],
    implies: ["main-course", "meal", "savoury-food", "sushi", "food"],
    related: ["country-japan"],
  }),
  tag("tacos-meal", {
    label: "Tacos Meal",
    aliases: ["taco dinner"],
    parents: ["main-course", "taco"],
    implies: ["main-course", "meal", "savoury-food", "taco", "food"],
    related: ["country-mexico"],
  }),
  tag("thai-green-curry", {
    label: "Thai Green Curry",
    aliases: ["thai green curry"],
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-thailand"],
  }),
  tag("thai-red-curry", {
    label: "Thai Red Curry",
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-thailand"],
  }),
  tag("vegetable-stir-fry", {
    label: "Vegetable Stir Fry",
    parents: ["main-course", "meal"],
    implies: ["main-course", "meal", "savoury-food", "food"],
    related: ["country-china"],
  }),
];
