import { tag } from "../../tag";

export const savouryTags = [
  tag("burger", {
    label: "Burger",
    aliases: ["hamburger"],
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-united-states"],
  }),
  tag("burrito", {
    label: "Burrito",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-mexico"],
  }),
  tag("cooked-noodles", {
    label: "Cooked Noodles",
    aliases: ["noodle dish"],
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "cooking", "food"],
  }),
  tag("cooked-pasta", {
    label: "Cooked Pasta",
    aliases: ["pasta dish"],
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "cooking", "food"],
    related: ["country-italy"],
  }),
  tag("cooked-rice", {
    label: "Cooked Rice",
    aliases: ["rice dish"],
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "cooking", "food"],
  }),
  tag("dumplings", {
    label: "Dumplings",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-china"],
  }),
  tag("falafel", {
    label: "Falafel",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "protein", "food"],
  }),
  tag("fried-rice", {
    label: "Fried Rice",
    parents: ["cooked-rice"],
    implies: ["cooked-rice", "savoury-food", "meal", "food"],
  }),
  tag("fries", {
    label: "Fries",
    aliases: ["hot chips", "french fries"],
    parents: ["savoury-food", "snack"],
    implies: ["savoury-food", "snack", "food"],
    related: ["country-belgium", "country-france"],
  }),
  tag("hot-dog", {
    label: "Hot Dog",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-united-states"],
  }),
  tag("kebab", {
    label: "Kebab",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-turkiye"],
  }),
  tag("lasagne", {
    label: "Lasagne",
    aliases: ["lasagna"],
    parents: ["cooked-pasta"],
    implies: ["cooked-pasta", "savoury-food", "meal", "food"],
    related: ["country-italy"],
  }),
  tag("nachos", {
    label: "Nachos",
    parents: ["savoury-food", "snack"],
    implies: ["savoury-food", "snack", "food"],
    related: ["country-mexico"],
  }),
  tag("omelette", {
    label: "Omelette",
    aliases: ["omelet"],
    parents: ["savoury-food", "breakfast"],
    implies: ["savoury-food", "breakfast", "protein", "food"],
    related: ["country-france"],
  }),
  tag("pizza", {
    label: "Pizza",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-italy"],
  }),
  tag("ramen", {
    label: "Ramen",
    parents: ["cooked-noodles"],
    implies: ["cooked-noodles", "savoury-food", "meal", "food"],
    related: ["country-japan"],
  }),
  tag("salad-meal", {
    label: "Salad",
    aliases: ["prepared salad"],
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
  }),
  tag("sandwich", {
    label: "Sandwich",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-united-kingdom"],
  }),
  tag("savoury-pie", {
    label: "Savoury Pie",
    aliases: ["meat pie", "pot pie"],
    parents: ["savoury-food", "baked-good", "meal"],
    implies: ["savoury-food", "baked-good", "meal", "food"],
  }),
  tag("savoury-tart", {
    label: "Savoury Tart",
    aliases: ["quiche"],
    parents: ["savoury-food", "baked-good"],
    implies: ["savoury-food", "baked-good", "food"],
    related: ["country-france"],
  }),
  tag("soup", {
    label: "Soup",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
  }),
  tag("stew", {
    label: "Stew",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
  }),
  tag("sushi", {
    label: "Sushi",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-japan"],
  }),
  tag("taco", {
    label: "Taco",
    parents: ["savoury-food", "meal"],
    implies: ["savoury-food", "meal", "food"],
    related: ["country-mexico"],
  }),
  tag("toastie", {
    label: "Toastie",
    aliases: ["grilled cheese", "toasted sandwich"],
    parents: ["sandwich", "savoury-food"],
    implies: ["sandwich", "savoury-food", "meal", "food"],
  }),
];
